### ISSUE TITLE
[Bug Report] Can't publish to macOS store

### ISSUE THREAD

**Issue by HankG** [alexmercerind/media_kit#106]
When trying to publish a macOS app to the store the archive is pulled during the processing phase and I get an email about malformed framework files. Each of the framework files produces the same error so I'm just putting one of them in here. I had no problem publishing to the iOS app to the store.

ITMS-90291: Malformed Framework -  The framework bundle (Relatica.app/Contents/Frameworks/Avcodec.framework) must contain a symbolic link 'Avcodec' -> 'Versions/Current/Avcodec'. Refer to the Anatomy of Framework Bundles for more information.               	ITMS-90291: Malformed Framework -  The framework bundle (Relatica.app/Contents/Frameworks/Avcodec.framework) must contain a symbolic link 'Resources' -> 'Versions/Current/Resources'. Refer to the Anatomy of Framework Bundles for more information.               	ITMS-90292: Malformed Framework -  The framework bundle (Relatica.app/Contents/Frameworks/Avcodec.framework) 'Versions' directory must contain a symbolic link 'Current' resolving to a specific version directory. Resolved link target: '${linkTarget}'. Refer to the Anatomy of Framework Bundles for more information. | ITMS-90291: Malformed Framework -  The framework bundle (Relatica.app/Contents/Frameworks/Avcodec.framework) must contain a symbolic link 'Avcodec' -> 'Versions/Current/Avcodec'. Refer to the Anatomy of Framework Bundles for more information.               	ITMS-90291: Malformed Framework -  The framework bundle (Relatica.app/Contents/Frameworks/Avcodec.framework) must contain a symbolic link 'Resources' -> 'Versions/Current/Resources'. Refer to the Anatomy of Framework Bundles for more information.               	ITMS-90292: Malformed Framework -  The framework bundle (Relatica.app/Contents/Frameworks/Avcodec.framework) 'Versions' directory must contain a symbolic link 'Current' resolving to a specific version directory. Resolved link target: '${linkTarget}'. Refer to the Anatomy of Framework Bundles for more information.
-- | --
ITMS-90291: Malformed Framework -  The framework bundle (Relatica.app/Contents/Frameworks/Avcodec.framework) must contain a symbolic link 'Avcodec' -> 'Versions/Current/Avcodec'. Refer to the Anatomy of Framework Bundles for more information.               	ITMS-90291: Malformed Framework -  The framework bundle (Relatica.app/Contents/Frameworks/Avcodec.framework) must contain a symbolic link 'Resources' -> 'Versions/Current/Resources'. Refer to the Anatomy of Framework Bundles for more information.               	ITMS-90292: Malformed Framework -  The framework bundle (Relatica.app/Contents/Frameworks/Avcodec.framework) 'Versions' directory must contain a symbolic link 'Current' resolving to a specific version directory. Resolved link target: '${linkTarget}'. Refer to the Anatomy of Framework Bundles for more information.

ITMS-90291: Malformed Framework - The framework bundle (Relatica.app/Contents/Frameworks/Avcodec.framework) must contain a symbolic link 'Avcodec' -> 'Versions/Current/Avcodec'. Refer to the [Anatomy of Framework Bundles](http://developer.apple.com/library/mac/#documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html) for more information. 

ITMS-90291: Malformed Framework - The framework bundle (Relatica.app/Contents/Frameworks/Avcodec.framework) must contain a symbolic link 'Resources' -> 'Versions/Current/Resources'. Refer to the [Anatomy of Framework Bundles](http://developer.apple.com/library/mac/#documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html) for more information. 

ITMS-90292: Malformed Framework - The framework bundle (Relatica.app/Contents/Frameworks/Avcodec.framework) 'Versions' directory must contain a symbolic link 'Current' resolving to a specific version directory. Resolved link target: '${linkTarget}'. Refer to the [Anatomy of Framework Bundles](http://developer.apple.com/library/mac/#documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html) for more information.

**Comment by birros** [comment]
The problem is identified, the framework format is not the same between iOS & macOS....
So I have to modify my scripts!
Thx Apple…
