### ISSUE TITLE
[Bug Report] Sometimes mpv is played in a native popup window

### ISSUE THREAD

**Issue by birros** [alexmercerind/media_kit#108]
Sometimes, when I play a video, in my app and not in `media_kit_test`, the video doesn't display in the Flutter texture but in a native window, like a popup, as if mpv had been launched from the cli.

I can't reproduce this every time. It has happened several times after a reboot of the OS or after a suspend.

I think this is caused by the initialization duration of `TextureHW.swift`, since it trigger a texture update with an empty size before the asynchronous initialization.
media_kit starts playing before the renderer is initialized, which triggers the native window to open.
I will check this tomorrow.

**Comment by birros** [comment]
Ok, I found the problem, it comes from my implementation in my application, not from `media_kit`...
I call `Player.play` before `VideoController.create` is completed...
Sorry...

---

But... I think the developer's experience is wrong, by default no native window should open, i.e. the `vo` should be set to `"null"` (not `null`).
It should be the responsibility of `media_kit_video`, when called by `VideoController.create`, to replace the value of `vo` (e.g. with `libmpv`).
To get the native mpv window by default, as is currently the case, just use `null` (not `"null"`).

---

So the PR would be very simple, only a few lines to change:

https://github.com/alexmercerind/media_kit/blob/c71d6725dafff4045ed66cd711b10a8f4069bf11/media_kit/lib/src/platform_player.dart#L110-L120

```diff
const PlayerConfiguration({
    this.events = true,
    this.logLevel = MPVLogLevel.none,
    this.osc = false,
    this.vid,
-   this.vo,
+   this.vo = "null",
    this.pitch = false,
    this.libmpv,
    this.title,
    this.ready,
  });
```

And for example for macOS & iOS:

https://github.com/alexmercerind/media_kit/blob/c71d6725dafff4045ed66cd711b10a8f4069bf11/media_kit_video/macos/Classes/TextureHW.swift#L63

```diff
+ MPVHelpers.checkError(mpv_set_option_string(handle, "vo", "libmpv"))
MPVHelpers.checkError(mpv_set_option_string(handle, "hwdec", "auto"))
```

I think the same is true for Windows and Linux.

**Comment by alexmercerind** [comment]
I did mention in the primary README to create `VideoController` before `open` or `play` commands.

`vid=no` is a more likable approach as compared to `vo=null` because later still decodes the video in the background.

Although, since package:media_kit is made to run solely in Dart without Flutter, I don't know how good of a decision it will be to disable video output by default.
But... Since 99.9% of our dependents will be Flutter applications & considering all Flutter developers are normies, I'm totally down with it. I'll make sure.
