### ISSUE TITLE
[Bug Report] media_kit_native_event_loop forces build to fail if libs_* package for that platform is not added

### ISSUE THREAD

**Issue by bdlukaa** [alexmercerind/media_kit#109]
### Edit by @alexmercerind:

As the name suggests, [package:media_kit_native_event_loop](https://pub.dev/packages/media_kit_native_event_loop) is a native dependency which links to the shared libraries offered by package:media_kit_libs_* packages. e.g.
- package:media_kit_libs_windows_video
- package:media_kit_libs_android_video
- package:media_kit_libs_macos_video
- package:media_kit_libs_ios_video

You must have them in your `pubspec.yaml` file, in order to get native event loop working.

### Original comment:

It looks like `media_kit_native_event_loop` is not building on iOS.

**Logs**

```
In file included from /Users/runner/hostedtoolcache/flutter/master-master-x64/.pub-cache/git/media_kit-c71d6725dafff4045ed66cd711b10a8f4069bf11/media_kit_native_event_loop/ios/Classes/media_kit_native_event_loop.cc:3:
            In file included from /Users/runner/hostedtoolcache/flutter/master-master-x64/.pub-cache/git/media_kit-c71d6725dafff4045ed66cd711b10a8f4069bf11/media_kit_native_event_loop/ios/Classes/../../src/media_kit_native_event_loop.cc:9:
            /Users/runner/hostedtoolcache/flutter/master-master-x64/.pub-cache/git/media_kit-c71d6725dafff4045ed66cd711b10a8f4069bf11/media_kit_native_event_loop/ios/Classes/../../src/media_kit_native_event_loop.h:17:10: fatal error: 'mpv/client.h' file not found
            #include <mpv/client.h>
                     ^~~~~~~~~~~~~~
            1 error generated.
```

**Additional information**

https://github.com/bluecherrydvr/unity/actions/runs/4613699398/jobs/8155955124?pr=90

**Comment by birros** [comment]
Please use the last numbered version or the latest commit.

**Comment by bdlukaa** [comment]
@birros I tried (https://github.com/bluecherrydvr/unity/commit/e0460f6ba8c238dca34298425db2f8267d2e5470), but same issue

**Comment by birros** [comment]
Ok, add `media_kit_libs_ios_video`, it will work.

**Comment by birros** [comment]
@bdlukaa You are not the first, nor the last to forget a package, it happens to everyone ^^
I think we'll add a help message to remind dev to install the missing package, your problem will have been useful for that 🙂

**Comment by alexmercerind** [comment]
Add the dependencies we suggested isn't the most difficult task to do. Even if it built... it wouldn't have worked.

**Comment by alexmercerind** [comment]
This reminds me of:

[video.webm](https://user-images.githubusercontent.com/28951144/230049425-47f9bd5c-20e2-4cdd-b166-a80e8de7f6a6.webm)

**Comment by alexmercerind** [comment]
BTW, you should consider switching to media_kit on iOS too. It's far better.

[package:fijkplayer](https://github.com/bdlukaa/fijkplayer) is receiving zero maintenance & I had to fork it myself to fix an invalid memory access on iOS.
Also, package:media_kit for Android (#100) will be out soon.

**Comment by bdlukaa** [comment]
> Because macOS & iOS weren't even added back then.

I see. It was just an unexpected breaking change for me.

> BTW, you should consider switching to package:media_kit on iOS too. It's far better.

Yeah, I'm just waiting for Android support to be added to get rid of the old dependencies. Because Flutter can not limit package binaries per platform, I need support for both mobile platforms to get it working.

**Comment by birros** [comment]
Ok, I finally understand the problem ^^

Unfortunately, I think it's technically impossible to include `media_kit_video` or `media_kit_native_event_loop` as a dependency without `media_kit_libs_ios_video` when building for iOS. And vice versa for macOS.

Because `media_kit_video` and `media_kit_native_event_loop` use a `.podspec` to link to native libraries, or AFAIK it is impossible to add a condition to check at compile time whether the libraries are present or not.
A `.podspec` is not as flexible as a Makefile.

**Comment by birros** [comment]
From Discord: A possible approach would be to do as `media_kit` did for the `Player`, dynamically load the library at runtime. There is no need to link the library natively, so no more errors at compile time, an error is only triggered if the native code is executed.
