### ISSUE TITLE
[RFC] Goals for 1.0.0

### ISSUE THREAD

**Issue by alexmercerind** [alexmercerind/media_kit#114]
Currently, [package:media_kit](https://github.com/alexmercerind/media_kit) is under active development.
The work that's been released is very performant & stable for usage. It is already being used by some FOSS applications.

Before a 1.0.0, I/we want to **ensure a perfectly stable experience & feature/future proof API** for everyone.
Few of the important tasks (besides the major ones which are already completed) that I have in mind:

- [x] Android support
- [x] Android optimizations
- [x] Web support
- [x] Web optimizations
- [x] Destroying `Player` instances upon hot-restart & package entry-point
- [x] Reducing bundle size of video dependencies for Windows
- [x] Audio only dependencies for macOS & iOS
- [x] ~~Documentation (website?)~~
  - ~~#92~~
- [x] In-built video UI controls & widgets e.g. slider, play-pause, brightness/volume, custom buttons etc. 
- [x] Lazy binding in package:media_kit_native_event_loop & package:media_kit_video
  - #109
  - #113
- [x] `VideoController.setSize` API
  - #84
  - #85

Once we are 1.0.0 & have a stable experience for our dependents, I/we would like to move onto some long-term tasks.
e.g.

- Further improving performance even more.
  - NOTE: [package:media_kit](https://github.com/alexmercerind/media_kit) is already outperforming Google Chrome & default Media Player in Windows 11.
- A `media_kit_*` package for extracting thumbnails.
- A `media_kit_*` package for reading media metadata.
- A `media_kit_*` package for native OS controls which automatically registers with a `Player`.
- Contributing back to Flutter framework & engine.
- Contributing back to mpv.

<hr>

If you're interested in contributing, please do not hesitate.
Contributions like improving documentation & adding `Video` UI widgets etc. are fairly easy & very valuable for the project! 💫

**Comment by alexmercerind** [comment]
Further details may be found in ["Goals" section of the README](https://github.com/alexmercerind/media_kit#goals).
["Architecture"](https://github.com/alexmercerind/media_kit#architecture) & ["Implementation"](https://github.com/alexmercerind/media_kit#implementation) sections provide information about project's implementation & source-code structure.

**Comment by alexmercerind** [comment]
1.0.0 is now available! 🎉

**Comment by wengxianxun** [comment]
A media_kit_* package for reading media metadata.

need this . tk
