### ISSUE TITLE
[Question] How to play without opening mpv player?

### ISSUE THREAD

**Issue by AndroidDesigner** [alexmercerind/media_kit#115]
Hi.
Thank you for this amazing player!

I'm using this package in a Linux Ubuntu OS. 
I want to use my own UI to create a player UI. So how can I play an audio without opening the mpv player?

**Comment by alexmercerind** [comment]
```dart      
final player = Player(
  configuration: PlayerConfiguration(
    /// Pass vid: false.
    vid: false,
  ),
);
```

This will disable default window output. Close if solved.

**Comment by alexmercerind** [comment]
Works?

**Comment by AndroidDesigner** [comment]
Thank you so much.
it worked!
