### ISSUE TITLE
Add Feature: Metadata of Audio or Video

### ISSUE THREAD

**Issue by moshOntong-IT** [alexmercerind/media_kit#117]
The team should add a feature to get the metadata of particular audio or video file. And why?
The reason is that it is important to get some info about the file and also I think it is helpful to us especially to get the duration of the file. If this feature is already exist, then can you please give a example code for that.

**Comment by alexmercerind** [comment]
Read: [[RFC] Goals for 1.0.0](https://github.com/alexmercerind/media_kit/issues/114). This is out of scope for now. I don't want to support it.

**Comment by wengxianxun** [comment]
i need get video Metadata too
