### ISSUE TITLE
mpv-dev.7z seems corrupt

### ISSUE THREAD

**Issue by Leadrive** [alexmercerind/media_kit#12]
cd media_kit_test
flutter build windows

report error
mpv-dev.7z seems corrupt

How to download the mpv-dev.7z?

**Comment by alexmercerind** [comment]
https://github.com/alexmercerind/mpv-win32-build/releases/tag/20221227

**Comment by alexmercerind** [comment]
Make sure your computer can connect to GitHub during build process.
Do a `flutter clean` & try again.

**Comment by Leadrive** [comment]
thank you, build success.
