### ISSUE TITLE
[Question] VideoController.create now takes player & instead of player.handle

### ISSUE THREAD

**Issue by Bullets-jyr** [alexmercerind/media_kit#120]
await VideoController.create(player); not working
please check pub.dev media_kit_video because the media_kit_video source on Github and the media_kit_video source from pub.dev are different.

[Error Log]
Error: The argument type 'Player' can't be assigned to the parameter type 'Future<int>'.
 - 'Player' is from 'package:media_kit/src/player.dart' ('../../.pub-cache/hosted/pub.dev/media_kit-0.0.4+1/lib/src/player.dart').
 - 'Future' is from 'dart:async'.
      controller = await VideoController.create(player);

**Comment by alexmercerind** [comment]
Please don't mix the package(s) from two sources (GitHub & pub.dev).

Since the project is in very active development, there are few changes that we're making until we are 1.0.0 (#114 ).

**Comment by alexmercerind** [comment]
In summary, version on GitHub (& next update) makes this change:

- `VideoController.create` now takes `player` & instead of `player.handle`.

This is important to support Android & improve surface API. I hope that clears it.

**Comment by alexmercerind** [comment]
I hope the question is answered.

**Comment by alexmercerind** [comment]
Make sure you have added it to `pubspec.yaml` & done a hot-restart.

**Comment by Bullets-jyr** [comment]
class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  /// Create a [Player].
  final Player player = Player();

  /// Store reference to the [VideoController].
  VideoController? controller;

  @override
  void initState() {
    super.initState();
    Future.microtask(() async {
      await player.open(Media('asset:///videos/bee.mp4'));
      /// Create a [VideoController] to show video output of the [Player].
      controller = await VideoController.create(player.handle);
      setState(() {});
    });
  }

  @override
  void dispose() {
    Future.microtask(() async {
      /// Release allocated resources back to the system.
      await controller?.dispose();
      await player.dispose();
    });
    super.dispose();
  }

  void onPlayPressed() async {
    await player.play();
  }

  @override
  Widget build(BuildContext context) {
    /// Use [Video] widget to display the output.
    return Stack(
      children: [
        GestureDetector(
          onTap: onPlayPressed,
          child: Video(
            /// Pass the [controller].
            controller: controller,
          ),
        ),
      ],
    );
  }
}

this is my code Can you tell me which part is wrong?

**Comment by Bullets-jyr** [comment]
<img width="278" alt="스크린샷 2023-04-11 오후 8 07 08" src="https://user-images.githubusercontent.com/117099209/231142368-47a5ea3c-bcd2-4934-9c5e-e0443808f21f.png">

**Comment by Bullets-jyr** [comment]
class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  /// Create a [Player].
  final Player player = Player();

  /// Store reference to the [VideoController].
  VideoController? controller;

  @override
  void initState() {
    super.initState();
    Future.microtask(() async {
      await player.open(Media('asset:///videos/sample1.mp4'));
      /// Create a [VideoController] to show video output of the [Player].
      controller = await VideoController.create(player.handle);
      setState(() {});
    });
  }

  @override
  void dispose() {
    Future.microtask(() async {
      /// Release allocated resources back to the system.
      await controller?.dispose();
      await player.dispose();
    });
    super.dispose();
  }

  void onPlayPressed() async {
    await player.play();
  }

  @override
  Widget build(BuildContext context) {
    /// Use [Video] widget to display the output.
    return Stack(
      children: [
        GestureDetector(
          onTap: onPlayPressed,
          child: Video(
            /// Pass the [controller].
            controller: controller,
          ),
        ),
      ],
    );
  }
}

**Comment by alexmercerind** [comment]
@Bullets-jyr, you may try playing some online URL or File path.

Chances are your asset is not synced. Have you added it to `pubspec.yaml`?

**Comment by alexmercerind** [comment]
Also, `videos/bee.mp4` is different than `assets/videos/sample1.mp4`.

You need to add it to `pubspec.yaml`!!!

**Comment by Bullets-jyr** [comment]
assets:
    - assets/images/
    - assets/videos/
As you said, it is added to pubspec.yaml.

**Comment by Bullets-jyr** [comment]
await player.open(Media('assets:///videos/sample1.mp4')); I wrote the code.

**Comment by alexmercerind** [comment]
https://github.com/alexmercerind/media_kit/blob/c920eba48e85e7cb49a2181783f20bb844c1d27b/media_kit_test/pubspec.yaml#L57-L62

**Comment by alexmercerind** [comment]
Incorrect:

```dart
await player.open(Media('assets:///videos/sample1.mp4'));
```

Correct:

```dart
await player.open(Media('assets:///assets/videos/sample1.mp4'));
```

**Comment by Bullets-jyr** [comment]
[Code]
class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  /// Create a [Player].
  final Player player = Player();

  /// Store reference to the [VideoController].
  VideoController? controller;

  @override
  void initState() {
    super.initState();
    Future.microtask(() async {
      await player.open(Media('assets:///assets/videos/sample1.mp4'));
      /// Create a [VideoController] to show video output of the [Player].
      controller = await VideoController.create(player.handle);
      setState(() {});
    });
  }

  @override
  void dispose() {
    Future.microtask(() async {
      /// Release allocated resources back to the system.
      await controller?.dispose();
      await player.dispose();
    });
    super.dispose();
  }

  void onPlayPressed() async {
    await player.play();
    print('Click onPlayPressed');
  }

  @override
  Widget build(BuildContext context) {
    /// Use [Video] widget to display the output.
    return Stack(
      children: [
        GestureDetector(
          onTap: onPlayPressed,
          child: Video(
            /// Pass the [controller].
            controller: controller,
          ),
        ),
      ],
    );
  }
}

[pubspec.yaml]
  assets:
    - assets/images/
    - assets/videos/sample1.mp4

Unfortunately, it doesn't play. help.

**Comment by Bullets-jyr** [comment]
<img width="1150" alt="스크린샷 2023-04-11 오후 8 20 03" src="https://user-images.githubusercontent.com/117099209/231145707-8e01dc8f-8728-44f3-b975-5b3c290526ce.png">
The log comes out, but the video doesn't play.

**Comment by alexmercerind** [comment]
May we talk at our Discord: https://discord.gg/h7qf2R9n57 ?
