### ISSUE TITLE
Does not handle Japanese character

### ISSUE THREAD

**Issue by CaptainDario** [alexmercerind/media_kit#121]
FIrst of all, thank you for this brillant package!
However, I had some problems getting started because this package does not seem to handle some characters (correctly).

I have a file called `う.wav` which cannot be played. I think this is not a problem but there is on error message (or anything) indicating that the name is the problem, the sound just does not play. Renaming the file to `u.wav` resolved the issue

I am converting from `just_audio` to this package (in just audio the name works) and this took me quite some time to figure out, therefore, a note somewhere would be nice (in my opinion).

**Comment by alexmercerind** [comment]
> First of all, thank you for this brillant package!

It's a really big goal & we're trying our best. Please see: [[RFC] Goals for 1.0.0](https://github.com/alexmercerind/media_kit/issues).
An aim to act as a complete, performant & stable solution across all platforms for both audio & video playback.

> However, I had some problems getting started because this package does not seem to handle some characters (correctly).
> 
> I have a file called `う.wav` which cannot be played. I think this is not a problem but there is on error message (or anything) indicating that the name is the problem, the sound just does not play. Renaming the file to `u.wav` resolved the issue
> 
> I am converting from `just_audio` to this package (in just audio the name works) and this took me quite some time to figure out, therefore, a note somewhere would be nice (in my opinion).

Just for further details, is this happening on Windows?

**Comment by CaptainDario** [comment]
You are right, I should have added more details.

I am on: Flutter (Channel stable, 3.7.3, on macOS 13.3.1 22E261 darwin-arm64)
Flutter is 
I tried to load the file like this

``` dart
final Player player = Player();

await kanaSoundPlayer.open(
  Media("asset://assets/audios/kana/individuals/う.wav"),
  play: true
);
```

I looked a bit at the code of media kit to 'understand' the problem. When you initialise the `Media()`-Object you are encoding the passed asset path, which results into the Japanese characters being converted to something else. I think now encoding the path when using assets should resolve it (I am unsure how safe this is though).

**Comment by alexmercerind** [comment]
Thanks a lot for taking a detailed look. You may even raise as a PR if you feel like it.

Also, please note that we're still working on audio-only (less sized) binaries for macOS & iOS.
Each platform has "libs" package like:
- media_kit_libs_android_audio
- media_kit_libs_android_video
- media_kit_libs_windows_audio
- media_kit_libs_windows_video

macOS & iOS are WIP. They should be out sometime this week.

**Comment by alexmercerind** [comment]
Hi @CaptainDario,

PR: #122 should resolve it. A confirmation from your end would be great.

Thanks!

**Comment by CaptainDario** [comment]
@alexmercerind 
Thanks for the quick PR! Otherwise I would have tried to create PR.

It works great, I added

```yaml
media_kit: 
    git:
      url: https://github.com/alexmercerind/media_kit
      path: media_kit
      ref: fix/121
``` 

to my pubspec and the characters work now for assets.

Thank you also for the note for audio only libs, but I am planning to add audio and video support, so I am okay with bigger binary.
Any rough estimate when this fix gets published to pub.dev?

**Comment by CaptainDario** [comment]
One idea for an improvement, I think it would be nice to get some kind of error / message when the asset is not found. Otherwise, it is quite difficult to verify what the actual issue is.

For example, FlutterSVG shows this

```
Exception has occurred.
FlutterError (Unable to load asset: "assets/images/kana/individuals/う.svg".
The asset does not exist or has empty data.)
```

**Comment by CaptainDario** [comment]
@alexmercerind after some more investigation there seems to still be some kind of issues.

う.wav works, however, characters with Dakuten (ex.: だ) do not work.

**Comment by birros** [comment]
@CaptainDario On macOS? Are you sure?
I just checked, the following code works (#122):
```dart
final Player player = Player();
await player.open(
  Media("asset://assets/だ.wav"),
  play: true,
);
```

---

Check that the asset is present in your application:
```dart
final manifestContent = await rootBundle.loadString('AssetManifest.json');
print(manifestContent);
```

**Comment by birros** [comment]
Tested with Flutter versions `3.7.3` and `3.7.10`.
I confirm, the following code works:
```dart
final Player player = Player();
await player.open(
  Media("asset://assets/audios/kana/individuals/だ.wav"),
  play: true,
);
```

Can you try from scratch in `media_kit_test`, maybe it's a problem specific to your application.

**Comment by birros** [comment]
Check that the asset file is present in the build output, and it's valid:
```shell
$ mpv build/macos/Build/Products/Release/media_kit_test.app/Contents/Frameworks/App.framework/Versions/A/Resources/flutter_assets/assets/audios/kana/individuals/%E3%81%A0.wav
```

**Comment by CaptainDario** [comment]
Here one more detail, the two characters encoded with `Uri.encode`

```
さ + ゛-   %E3%81%BB%E3%82%9A
ざ - %E3%81%BD
```

**Comment by CaptainDario** [comment]
Update: renaming the files does not work for me. When bundling the assets flutter / dart always automatically creates this combined version of the name.

I ende up writing the file names in roman letters ie.: だ -> da

**Comment by birros** [comment]
> I ende up writing the file names in roman letters ie.: だ -> da

It may also be wise not to use these characters for asset files, as the App Store may have blocking rules for such names.

**Comment by alexmercerind** [comment]
Maybe you can use MD5/SHA1 hash of these character(s) as file name.
A simple script can help you rename your files in bulk. By using a hashing algorithm, you'll be able to avoid the requirement of storing any indexing/mapping etc. I never really included any assets with special characters in my code-base.

I wonder how Flutter internally decides the names of these assets. If it's a Dart sided logic, we can copy the same.
