### ISSUE TITLE
media_kit_test can not play on Ubuntu

### ISSUE THREAD

**Issue by Leadrive** [alexmercerind/media_kit#13]
Non-C locale detected. This is not supported.
Call 'setlocale(LC_NUMERIC, "C");' in your code.

**Comment by alexmercerind** [comment]
Linux project isn't generated yet.
However, audio support is ready for Linux, **video support is a work-in-progress**.

You need this:

https://github.com/harmonoid/harmonoid/blob/7597ad795104ef18b6b888c7d4d71448411f1b7a/linux/my_application.cc#L13
https://github.com/harmonoid/harmonoid/blob/7597ad795104ef18b6b888c7d4d71448411f1b7a/linux/my_application.cc#L34

**Comment by alexmercerind** [comment]
Fixed?

**Comment by Leadrive** [comment]
Yes, I can play now.
Thank you.

**Comment by alexmercerind** [comment]
FYI, Linux support is now added.
