### ISSUE TITLE
CPU over 200%

### ISSUE THREAD

**Issue by Ormosia-ply** [alexmercerind/media_kit#133]
When media-kit not playing，CPU occupies 20%， but over 200% if playing. The platform is linux.
Please How can I solve this problem?

**Comment by alexmercerind** [comment]
Not specified:

- Media
- Code
- Logs
- Hardware

Video playback is not easy at it's core & definitely not as granted as exposed in a simple API. It can depend upon your code (how you have written it) or hardware (whether hardware rendering is possible) etc.

Nothing can be done for GNU/Linux, when there are issues like this:
- https://github.com/flutter/flutter/issues/88996
- https://github.com/flutter/flutter/issues/101591

As you can see, even a `CircularProgressIndicator` makes GNU/Linux embedder for Flutter take 50% of CPU. There isn't much that can be done by me to improve things. It's within GTK or Flutter. Let's see what future has.

Also: This is when GNU/Linux implementation is theoretically most efficient as compared to Windows or macOS.

For me, CPU usage is 10-20% on GNU/Linux. And 5-10% on Windows (still has large scope of improvement from my end!).

**Comment by Ormosia-ply** [comment]
> Not specified:
> 
> * Media
> * Code
> * Logs
> * Hardware
> 
> Video playback is not easy at it's core & definitely not as granted as exposed in a simple API. It can depend upon your code (how you have written it) or hardware (whether hardware rendering is possible) etc.
> 
> Nothing can be done for GNU/Linux, when there are issues like this:
> 
> * [High latency on frames on linux desktop flutter/flutter#88996](https://github.com/flutter/flutter/issues/88996)
> * [Linux Desktop: high CPU usage when running an animation flutter/flutter#101591](https://github.com/flutter/flutter/issues/101591)
> 
> As you can see, even a `CircularProgressIndicator` makes GNU/Linux embedder for Flutter take 50% of CPU. There isn't much that can be done by me to improve things. It's within GTK or Flutter. Let's see what future has.
> 
> Also: This is when GNU/Linux implementation is theoretically most efficient (as compared to Windows or macOS).
> 
> For me, CPU usage is 5-10% on Windows (still has large scope of improvement from my end) & 10-20% on GNU/Linux.


- When using media-kit to render video in flutter release mode, if the video is not played, the application will hardly occupy the cpu, but it will even exceed 100% when playing.

https://user-images.githubusercontent.com/78834739/232437427-88129a5a-0d2f-44d7-a321-435d4d22f3ad.mp4

https://user-images.githubusercontent.com/78834739/232437385-387fd195-0f8a-4dff-a964-076835c31224.mp4

- The video is in MP4 format, download it here: https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4.
- Hardware acceleration enabled.
- This video plays fine when using the mpv command.
- Problem reproduction.
1. pubspec.yaml
```dart
dependencies:
  flutter:
    sdk: flutter

  media_kit: ^0.0.4+1
  media_kit_video: ^0.0.4
  media_kit_native_event_loop: ^1.0.2
  media_kit_libs_linux: ^1.0.1

dependency_overrides:
  media_kit: 
    git:
      url: https://github.com/alexmercerind/media_kit.git
      path: media_kit
      ref: main
  media_kit_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      path: media_kit_video
      ref: main
  media_kit_native_event_loop: 
    git:
      url: https://github.com/alexmercerind/media_kit.git
      path: media_kit_native_event_loop
      ref: main
  media_kit_libs_linux:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      path: media_kit_libs_linux
      ref: main

flutter:
  uses-material-design: true
  assets:
    - videos/
```
2. main.dart
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

void main() {
  MediaKit.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final player = Player(
      configuration: const PlayerConfiguration(logLevel: MPVLogLevel.debug));
  VideoController? controller;

  @override
  void initState() {
    super.initState();
    Future.microtask(() async {
      controller = await VideoController.create(
        player,
        enableHardwareAcceleration: kReleaseMode,
      );
      await player.setPlaylistMode(PlaylistMode.loop);
      await player.open(Media('asset://videos/bee.mp4'), play: true);
      setState(() {});
    });
  }

  @override
  void dispose() {
    Future.microtask(() async {
      await controller?.dispose();
      await player.dispose();
    });
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Video(
        controller: controller,
        fit: BoxFit.cover,
      ),
    );
  }
}
```

**Comment by alexmercerind** [comment]
What do you see in the logs. Do you see following?

```
media_kit: VideoOutput: Using H/W rendering.
```

**Comment by Ormosia-ply** [comment]
```
package:media_kit_libs_linux registered.
media_kit: VideoOutput: video_output_new: 140407581445312
Cannot load libcuda.so.1
media_kit: VideoOutput: Using H/W rendering.
flutter: VideoOutput.Resize
flutter: {handle: 140407581445312, id: 140408520771088, rect: {left: 0, top: 0, width: 1, height: 1}}
flutter: VideoController: Texture ID: 140408520771088
media_kit: TextureGL: Resize: (1280, 720)
flutter: VideoOutput.Resize
flutter: {handle: 140407581445312, id: 140408520771088, rect: {left: 0, top: 0, width: 1280, height: 720}}
```
When the log is turned on, the console will not print.

**Comment by Ormosia-ply** [comment]
`perf` shows that `vaGetImage` is taking up most of the CPU time. Is it because decoding is accerelated but rendering is not?
![微信图片_20230417184703](https://user-images.githubusercontent.com/78834739/232463959-5e5d9e67-078f-48b8-b96b-78aba381ef3f.jpg)
![微信图片_20230417184648](https://user-images.githubusercontent.com/78834739/232463975-19208cf8-4d0b-4ca9-befb-e6450951652b.jpg)

**Comment by Ormosia-ply** [comment]
`vaGetImage` didn't show up when playing with `mpv` command.
![微信图片_20230418090251](https://user-images.githubusercontent.com/78834739/232642480-e6319823-2083-4c64-a1b7-c57e8dbbdb51.jpg)
