### ISSUE TITLE
audio is not playing in android for some url

### ISSUE THREAD

**Issue by solsticedhiver** [alexmercerind/media_kit#138]
In media_kit_test, on android, when trying to play https://arte-cmafhls.akamaized.net/am/cmaf-webonly/108000/108600/108672-013-A_VOF-STA/220524162741/medias/108672-013-A_v216.mp4 as video and https://arte-cmafhls.akamaized.net/am/cmaf-webonly/108000/108600/108672-013-A_VOF-STA/220524162741/medias/108672-013-A_aud_VOF.mp4 as the audio, I end up with video payling with no sound output and the following error in console:

```
W/ACodec  ( 7680): [OMX.android.goldfish.h264.decoder] BAD CODEC: Output format changed unexpectedly from (diff) AMessage(what = 0x00000000) = {
W/ACodec  ( 7680):       int32_t color-standard = 4
W/ACodec  ( 7680):       int32_t android._dataspace = 259
W/ACodec  ( 7680):     } to (diff) AMessage(what = 0x00000000) = {
W/ACodec  ( 7680):       int32_t color-standard = 1
W/ACodec  ( 7680):       int32_t android._dataspace = 260
W/ACodec  ( 7680):     }
```

this is working fine in linux

Note that the audio file is playing though, when you specify it as main file to play (aka video) in media_kist_test (single file  url)

**Comment by alexmercerind** [comment]
We have documented examples for using package.

If you are changing internal (libmpv) parameters/properties manually, I bet you shouldn't expect anything from us. Things work in a different way across platforms, that's how it is. I'd rather recommend creating two `Player` instances.

**Comment by solsticedhiver** [comment]
Did you read that I does not work in your media_kit_test? 
wt.!

**Comment by alexmercerind** [comment]
The membrane of my Android device's speakers does vibrate, propagating that motion to the air molecules around it. That wave; a vibratory disturbance in the medium around me is then received by my ears, generating electric pulses across my neurons giving me a sense of hearing an audio coming from my Android device when I play https://arte-cmafhls.akamaized.net/am/cmaf-webonly/108000/108600/108672-013-A_VOF-STA/220524162741/medias/108672-013-A_aud_VOF.mp4.

**Comment by solsticedhiver** [comment]
ok. So, the weird BAD CODEC message did not happened on a real device.

And the no sound issue appeared to be because of my code /o\. A simple *if* prevented the ':' of the url to be escaped like it should be on linux for audio url with '--audio-files' of mpv.

**Comment by birros** [comment]
:warning: For the record, I'd like to insist about `setProperty`, it is not officially exposed, and therefore not officially supported by `media_kit`…

---

`mpv` has made the most unwise choice about [string lists encoding](https://manpages.debian.org/bookworm/mpv/mpv.1.en.html#String_list_and_path_list_options):

> String lists are separated by ,. The strings are not parsed or interpreted by the option system itself. However, most
> Path or file list options use : (Unix) or ; (Windows) as separator, instead of ,.

So, as @solsticedhiver [says](https://github.com/alexmercerind/media_kit/issues/134#issuecomment-1511416437) don't forget to escape string items depending on the platform you are targeting:
- Unix: `:` -> `\\:`
- Windows: `;` -> `\\;`
