### ISSUE TITLE
[error] Trying to generate Player() in macOs emits null check error

### ISSUE THREAD

**Issue by hwr12** [alexmercerind/media_kit#139]
Hi,
You guys are awesome with probably the only macOs player in pub dev.
While implementing media_kit, I got an error saying,

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      NativeLibrary.path (package:media_kit/src/libmpv/core/native_library.dart:19:21)
#1      Player._create (package:media_kit/src/libmpv/player.dart:1121:63)
#2      new Player (package:media_kit/src/libmpv/player.dart:40:5)
#3      new Player (package:media_kit/src/player.dart:121:26)
#4      CommonStreamMediaKit._initController (package:streaming_repository/src/models/common_stream_media_kit.dart:19:20)
#5      new CommonStreamMediaKit.fromUri (package:streaming_repository/src/models/common_stream_media_kit.dart:14:18)
#6      StreamingRepository.createController (package:streaming_repository/src/streaming_repository.dart:47:37)
<asynchronous suspension>
#7      StreamCubit._generateController (package:jellyflut/screens/stream/cubit/stream_cubit.dart:269:24)
<asynchronous suspension>
#8      StreamCubit.init (package:jellyflut/screens/stream/cubit/stream_cubit.dart:39:13)
<asynchronous suspension>

<img width="457" alt="IntelliJ IDEA-2023 04 19 03 37-000972" src="https://user-images.githubusercontent.com/54504396/232872296-6bba9ab8-4976-4331-86c8-61244d512ee5.png">

I am using latest packages for media_kit , media_kit_video, media_kit_libs_macos_video.

**Comment by alexmercerind** [comment]
Call `MediaKit.ensureInitialized` as mentioned in README.
This is the last breaking change before v1.0.0.

**Comment by alexmercerind** [comment]
Close if works.

**Comment by hwr12** [comment]
It works thanks!!
