### ISSUE TITLE
additional arguments (lib)mpv for RTSP-Stream

### ISSUE THREAD

**Issue by filly82** [alexmercerind/media_kit#14]
My Local RTSP-Stream (TV-Stream via Router) needs an additional argument for mpv to work `--rtsp-transport=udp`

cmd: `mpv.exe "rtsp://..." --rtsp-transport=udp`

is this somehow currently possible or will be in future?

**Comment by Quackdoc** [comment]
might be possible to simply pass 

```
mpv_set_option_string(handle_, "rtsp-transport", "udp");
```

but I feel like MPV should implicitly handle this. I think you can specify UDP via URI can't you?

**Comment by alexmercerind** [comment]
Hi @filly82,

I did expose an API for setting libmpv properties/options from Dart.

```dart
final player = Player();
// Check type (only true for Windows & Linux).
if (player?.platform is libmpvPlayer) {
  await (player?.platform as libmpvPlayer?)?.setProperty("rtsp-transport", "udp");
}
```

In theory [this will work](https://github.com/harmonoid/harmonoid/blob/9ccc4ee116b5e4f19c462756403d5db9eb2def6f/lib/core/playback.dart#L324-L332). If it doesn't, sure let us know.
