### ISSUE TITLE
[Error] The video won't start in macOS with error

### ISSUE THREAD

**Issue by hwr12** [alexmercerind/media_kit#140]
Hi.
I have encountered error in macOS and the player won't start even though I press the play button of the player. 

flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Cannot add to an unmodifiable list
#0      UnmodifiableListMixin.add (dart:_internal/list.dart:114:5)
#1      Player.add (package:media_kit/src/libmpv/player.dart:251:27)
<asynchronous suspension>

<img width="1030" alt="IntelliJ IDEA-2023 04 19 04 10-000978" src="https://user-images.githubusercontent.com/54504396/232880801-460c2f6c-6e18-4e7e-8488-2153587afb97.png">

<img width="1724" alt="jellyflut-2023 04 19 04 09-000976" src="https://user-images.githubusercontent.com/54504396/232880449-8972fb0c-e31e-4227-9fbd-6e84d9a61fe6.png">

**Comment by alexmercerind** [comment]
Works for me :) See our test application.
No code, no potential solutions.

**Comment by hwr12** [comment]
It works now with the example code which uses player.open().
My code was using add() method which caused an error.

```dart
final player = Player();
final media = Media(uri.toString());
player.open(media);
```

Thanks!

**Comment by alexmercerind** [comment]
Also... Use await when you chain calls.

**Comment by hwr12** [comment]
> Also... Use await when you chain calls.

Ah ok got it :)
