### ISSUE TITLE
[Question] A problem occurred evaluating project ':media_kit_libs_android_video'

### ISSUE THREAD

**Issue by Ahmad0Tanveer** [alexmercerind/media_kit#142]
![image](https://user-images.githubusercontent.com/62099919/232940503-d1aed60c-880c-44b0-9e70-b1a4c9a94b80.png)

**Comment by alexmercerind** [comment]
You are unable to fetch dependencies from GitHub. Please try flutter clean. It's working for us, check out our latest CI run.

**Comment by alexmercerind** [comment]
https://github.com/alexmercerind/media_kit/actions/runs/4734069691
