### ISSUE TITLE
[Bug Report][Windows] crash on some devices

### ISSUE THREAD

**Issue by Kylart** [alexmercerind/media_kit#151]
#### Edit by @alexmercerind:

We are unable to replicate the crash on the number of Windows devices we tested project upon. If you are facing this issue, please reach us out so that we can identify the root cause & resolve the issue as quickly as possible.

#### Original comment:

I'm on Windows 10. The player keeps crashing with no error message when trying to play a video on the [Demo Windows app](https://github.com/alexmercerind/media_kit/releases/download/media_kit-v0.0.5/media_kit_test_win32_x64.7z).

Steps to reproduce on Windows 10.
1. [Download the available demo on the README](https://github.com/alexmercerind/media_kit/releases/download/media_kit-v0.0.5/media_kit_test_win32_x64.7z) 
2. Try to play any video

Maybe it's just my system but it used to work with previous versions.

**Comment by alexmercerind** [comment]
It's still working on my machine. May you please build the [`media_kit_test`](https://github.com/alexmercerind/media_kit/tree/main/media_kit_test) by cloning the repository?

It'd be great to resolve the issue as quickly as possible.

**Comment by alexmercerind** [comment]
If preferred, we may have an exchange in regards to fixing this at our Discord server: https://discord.gg/h7qf2R9n57

**Comment by Kylart** [comment]
I have the same results when building the `media_kit_test` folder after cloning the repo, no error message:
![image](https://user-images.githubusercontent.com/18316666/233801205-d7316fb1-68a7-4210-992b-220094d56180.png)


If you do prefer it I can show you my screen when doing it.

**Comment by alexmercerind** [comment]
Hi @Quackdoc!

Would you like to share some of your experience?

https://github.com/alexmercerind/media_kit/releases/download/media_kit-v0.0.5/media_kit_test_win32_x64.7z

Are you also facing crash with the latest build of test application?

**Comment by Quackdoc** [comment]
I tested app and compiled locally no issues. things to check off hand would be 

- flutter sdk version

and
- mpv's logs since it might be crashing (can grab them by passing `log-file location\log.txt` to libmpv)

**Comment by Quackdoc** [comment]
@Kylart if you are comfortable bisecting, you can make sure you are in the main repo, use the command `git bisect bad` then run `git checkout HASHHERE` you can grab the hash of any point in the repo, or if you know a specific tag, you can check via that too.

for instance if you think it worked on tag v0.0.4 you can do `git checkout --force git checkout media_kit-v0.0.4 --force`

then compile and run the test application, 

if it doesn't work go to an even older commit or tag, and try that. keep going until one works. continue to the next step when it does

if it worked, go back to the top of the repo, run `git bisect good` you will automatically change to a new commit, and should see something along the lines of 
```
Bisecting: ... (roughly 5 steps)
```

recompile and run the app, if it works, type `git bisect good` if it fails, run `git bisect bad`

keep doing this until you reach the end, it will spit out a commit log, at the top of it you will see commit information, we want the data that approximately looks like this

```
252cf5d4d9c4b7ab29301cdcdbbcf3c82220ae35 is the first bad commit
commit 252cf5d4d9c4b7ab29301cdcdbbcf3c82220ae35
Merge: 9d5baf5 7fbe2fe
Author: birros <birros@protonmail.com>
Date:   Wed Apr 12 16:30:00 2023 +0200

    Merge branch 'main' into feat/resize
```

copy that info here, sorry if I am less then coherent, it's 4:30 am

**Comment by alexmercerind** [comment]
From Discord:
> Alright I'm back home. I reset-ed my Windows and now it does not crash anymore. 🤷

The cause of crash was some unknown issue within the O/P's Windows installation/configuration. Issue could not be reproduced on any of Windows machines I could arrange.
