### ISSUE TITLE
How to set header, such as user-agent?

### ISSUE THREAD

**Issue by lance730** [alexmercerind/media_kit#152]
I want to play videos from internet, like this:
await player.open(Media("http://xx.mp4"));

I found this: Media(String resource, {dynamic extras})
user extras? how to write?
or somewhere to set options?

**Comment by alexmercerind** [comment]
> user extras? how to write?
> or somewhere to set options?

what?

**Comment by alexmercerind** [comment]
WIP : #147

**Comment by alexmercerind** [comment]
Secondly, browse existing issues: https://github.com/alexmercerind/media_kit/issues/59

**Comment by lance730** [comment]
Thanks!
