### ISSUE TITLE
local video playback issue

### ISSUE THREAD

**Issue by Fanom2813** [alexmercerind/media_kit#162]
hi, i am trying to play a local video `/data/user/0/com.example.gmtv/app_flutter/Van+Helsing+3+by+Vj+Lance.mp4` but it is only playing the audio only without video , however if i play the same file from online it everything works perfectly, what could be the issue .
thanks

**Comment by alexmercerind** [comment]
Your code is buggy then. Share & get reviewed if you wish.

**Comment by alexmercerind** [comment]
Add a `setState` after this:
```
controller = await VideoController.create(player);
```

**Comment by alexmercerind** [comment]
You can reach us out on Discord if you feel confused.
