### ISSUE TITLE
[Windows] Simultaneous Video & Player crash on texture/surface resize

### ISSUE THREAD

**Issue by GideonKock** [alexmercerind/media_kit#17]
The app crashes when I try to use 5 videos simultaneously. 

I'm getting the following error:

![](https://user-images.githubusercontent.com/98162132/211287756-2cefb4ed-630a-4ad2-a9f7-90b52bf38c73.png)

**Comment by alexmercerind** [comment]
Remove any dispose calls.

**Comment by GideonKock** [comment]
Unfortunately it still does.

**Comment by alexmercerind** [comment]
Thanks for the clarification. The example application also seems to crash for some reason (it didn't earlier) when playing two videos simultaneously. I will fix issues like this & it is the primary reason I haven't published the plugin yet. I will hold accountability for stability. I need some time.

<hr>

I'm actually busy with my semester examinations till the end of this month.
I will make further advancements & implementation(s) for other platforms after returning.

**Comment by alexmercerind** [comment]
A better clarification will be provided with the stacktrace of the crash. Use Visual Studio to do it (for debug build).

**Comment by alexmercerind** [comment]
Ping @Quackdoc:

For me, [this `glFinish` is crashing](https://github.com/alexmercerind/media_kit/blob/51b60f2eb6e6a60652e303a51b203fb4a0a6c9b2/media_kit_core_video/windows/video_output.cc#L148) with invalid memory access. The invalid memory access is taking place within the ANGLE DLL. I'm not sure about this one (at the moment), maybe this could be due to wrong usage or syncing issue?

I attempted to use single mutex for all `VideoOutput`s, the crash still takes place when playing multiple videos.
Try using the last section of the example application, where 2 videos can be played side by side.

**Comment by Quackdoc** [comment]
hmm, im getting sigterm even without that glfinish.

**Comment by alexmercerind** [comment]
A workaround is to pass fixed size from `VideoController.create` for now.

**Comment by alexmercerind** [comment]
Hi @GideonKock,

I've made a fix. Please try it out (confirmation is needed to keep the track), it shouldn't crash anymore.

**NOTE:** Flutter 3.7.x+ is needed from now on (beta or master channel at the time). This was partially due to bugs in Flutter itself.


You can download the test application for a quick look: https://github.com/alexmercerind/media_kit/actions/runs/3919351537. Select last option for playing 2 videos at once. AFAIK crash triggered when size of video changed or played for the first time. Your feedback after compiling/running your own application is also welcomed. It should work fine too.

![media_kit_test_fCkNB17CKX](https://user-images.githubusercontent.com/28951144/212485801-27bafb41-2caa-42c2-988b-59d886e60cc1.png)

**Comment by alexmercerind** [comment]
@GideonKock any feedback?

**Comment by GideonKock** [comment]
I'm still testing, but after upgrading the package, my own application still crashes with the same error, with and without dispose calls. I will do some tests and provide more information.

**Comment by alexmercerind** [comment]
Make sure that the package is _actually updated_. Git dependencies in `pubspec.yaml` generally don't sync.

You should specify `ref: 36b0681c61fcfe7283b07d7d4b67c8554e080e7b` (for both packages) as-well.
```yml
dependencies:
  media_kit:
    git: https://github.com/alexmercerind/media_kit.git
    path: media_kit
    ref: 36b0681c61fcfe7283b07d7d4b67c8554e080e7b
  media_kit_core_video:
    git: https://github.com/alexmercerind/media_kit.git
    path: media_kit_core_video
    ref: 36b0681c61fcfe7283b07d7d4b67c8554e080e7b

**Comment by alexmercerind** [comment]
And be on `master`/`beta` channel.

**Comment by GideonKock** [comment]
I'm getting the following error.

![Scherm­afbeelding 2023-01-16 om 10 53 46](https://user-images.githubusercontent.com/98162132/212650588-f364c2e9-c620-4e96-bd65-9d2976f33c7d.png)

**Comment by GideonKock** [comment]
I'm getting the following error:

![Scherm­afbeelding 2023-01-16 om 10 53 46](https://user-images.githubusercontent.com/98162132/212650979-baffce79-7755-4fbb-81e9-08c9cea370df.png)

**Comment by alexmercerind** [comment]
> And be on `master`/`beta` channel.

^^

**Comment by alexmercerind** [comment]
> Sorry, I was running on the stable channel. But after a flutter clean and pub get I get the following message:
> 
> ![image](https://user-images.githubusercontent.com/98162132/212690103-662f1bb3-871e-45b9-ba50-b5c80d666542.png)
> 

Please update ref to latest.

The links to one of dependencies was changed. Sorry won't happen again.

**Comment by GideonKock** [comment]
It's working :). Only with a material app. Unfortunately I use Fluent_ui and I get errors related to this packege when I'm on the master channel. Any suggestions?

**Comment by GideonKock** [comment]
Unfortunately the issue still occur. i have made an example. See the code below. The error only accurs with a valid url.

**Comment by GideonKock** [comment]
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int currentPageIndex = 0;
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
            primarySwatch: Colors.blue, scaffoldBackgroundColor: Colors.blue),
        home: DefaultTabController(
          length: 2,
          child: Scaffold(
            appBar: const TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
              ],
            ),
            body: TabBarView(
              children: [
                Wrap(
                  children: [
                    for (int i = 0; i < 1; i++) ...[
                      SizedBox(height: 500, width: 500, child: MyScreen())
                    ]
                  ],
                ),
                Wrap(
                  children: [
                    for (int i = 0; i < 2; i++) ...[
                      SizedBox(height: 500, width: 500, child: MyScreen())
                    ]
                  ],
                ),
              ],
            ),
          ),
        ));
  }
}

class MyScreen extends StatefulWidget {
  const MyScreen({Key? key}) : super(key: key);
  @override
  State<MyScreen> createState() => _MyScreenState();
}

class _MyScreenState extends State<MyScreen> {
  final Player player = Player();
  VideoController? controller;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      controller = await VideoController.create(
        player.handle,
      );
      player.open(Playlist(
        [
          Media(
              'https://....:...@192.168.2.120:55756/Acs/Streaming/Video/Live/Mp4/?camera=27074_196f745a-87e5-4325-ba5b-cda2d12026e7&quality=medium&audio=0'),
        ],
      ));
      setState(() {});
    });
  }

  @override
  void dispose() {
    Future.microtask(() async {
      // Release allocated resources back to the system.
      await controller?.dispose();
      await player.dispose();
    });
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Video(
      filterQuality: FilterQuality.high,
      controller: controller,
    );
  }
}

**Comment by GideonKock** [comment]
`import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

void main() {
runApp(const MyApp());
}

class MyApp extends StatefulWidget {
const MyApp({super.key});

@OverRide
State createState() => _MyAppState();
}

class _MyAppState extends State {
int currentPageIndex = 0;
@OverRide
Widget build(BuildContext context) {
return MaterialApp(
title: 'Flutter Demo',
theme: ThemeData(
primarySwatch: Colors.blue, scaffoldBackgroundColor: Colors.blue),
home: DefaultTabController(
length: 2,
child: Scaffold(
appBar: const TabBar(
tabs: [
Tab(icon: Icon(Icons.directions_car)),
Tab(icon: Icon(Icons.directions_transit)),
],
),
body: TabBarView(
children: [
Wrap(
children: [
for (int i = 0; i < 1; i++) ...[
SizedBox(height: 500, width: 500, child: MyScreen())
]
],
),
Wrap(
children: [
for (int i = 0; i < 2; i++) ...[
SizedBox(height: 500, width: 500, child: MyScreen())
]
],
),
],
),
),
));
}
}

class MyScreen extends StatefulWidget {
const MyScreen({Key? key}) : super(key: key);
@OverRide
State createState() => _MyScreenState();
}

class _MyScreenState extends State {
final Player player = Player();
VideoController? controller;

@OverRide
void initState() {
super.initState();
WidgetsBinding.instance.addPostFrameCallback((_) async {
controller = await VideoController.create(
player.handle,
);
player.open(Playlist(
[
Media(
'https://....:...@192.168.2.120:55756/Acs/Streaming/Video/Live/Mp4/?camera=27074_196f745a-87e5-4325-ba5b-cda2d12026e7&quality=medium&audio=0'),
],
));
setState(() {});
});
}

@OverRide
void dispose() {
Future.microtask(() async {
// Release allocated resources back to the system.
await controller?.dispose();
await player.dispose();
});
super.dispose();
}

@OverRide
Widget build(BuildContext context) {
return Video(
filterQuality: FilterQuality.high,
controller: controller,
);
}
}`

**Comment by Quackdoc** [comment]
you are disposing the controller

**Comment by alexmercerind** [comment]
Can't reproduce. Present more details, what is the extent & what is the cause.
Use Visual Studio to generate stack-trace.

**Comment by GideonKock** [comment]
Yes, this was mentioned in the example on the mainpage. So I only have to dispose the player?

**Comment by alexmercerind** [comment]
> Yes, this was mentioned in the example on the mainpage. So I only have to dispose the player?

What makes you so sure that your `async` calls to create/dispose don't cause some conflict when changing tabs? The test application is playing/creating/disposing 4 videos simultaneously without any races or access violations etc.

C++ isn't for kids. It doesn't kindly inform you about invalid memory accesses with a nice message. A debugger works here e.g. `devenv` or Visual Studio.

**Comment by GideonKock** [comment]
Without disposing the controller the error no longer appears. 

With disposing the controller, the error appears when choosing the other tab and then back. Also when switch tabs slowly.

I've used the debugger in Visual Studio as you mentioned. I hope this is the information you need:

![image](https://user-images.githubusercontent.com/98162132/215448888-a9219aa0-4eb0-4f5a-8526-4ab73b1a9bef.png)

**Comment by alexmercerind** [comment]
It's invalid memory access or access violation as I said. I'm not super sure about what could be causing it.

I will try fixing tomorrow & begin working on linux implementation.

**Comment by alexmercerind** [comment]
@GideonKock, try out the latest changes on 8cecec270fcb616e4154583a343d6b7330a02f86.

Specify `ref` as `8cecec270fcb616e4154583a343d6b7330a02f86` in your pubspec.yaml for both packages.

**Comment by alexmercerind** [comment]
There was an issue within my implementation of releasing EGL resources inside ANGLESurfaceManager destructor.
Now calling dispose won't crash (and it's important to release resources, please don't remove it).

<hr>

Still, I'm facing few very rare crashes within libGLESv2.dll through libmpv-2.dll when dragging through tabs using my track-pad, so there's very little that can be done. Let's see what can I do (possibly compiling own ANGLE after silencing these silly assertions).

A GOOD IDEA WILL BE TO manage your `VideoController` & `Player` efficiently instead of depending on `initState` etc.

**Comment by alexmercerind** [comment]
I'd appreciate response though. Any improvements?

**Comment by GideonKock** [comment]
Nice! Sorry, but I’m not able tot test it today. Will do it tomorrow. But it seems very good. Much appriciated!

**Comment by alexmercerind** [comment]
Any feedback?

**Comment by GideonKock** [comment]
In my own application it still crashes. Only difference compared to the example application is that I use multiple streams at one tab. Will test it tomorrow in the example application.

**Comment by alexmercerind** [comment]
Best practice will be to maintain the `Player` & `VideoController` instances outside of `Tab`s & only pass their reference into the widgets. It will give you not only finer control over lifecycle but improve performance as you can possibly use already created `Player`s within multiple tabs (as previous one automatically gets hidden).

**Comment by GideonKock** [comment]
Thanks, will try to implement. Multiple video's in a tab in your test application works without errors.
