### ISSUE TITLE
[Enhancement] first frame loading state exposure

### ISSUE THREAD

**Issue by clragon** [alexmercerind/media_kit#171]
As seen in [test 06](https://github.com/alexmercerind/media_kit/blob/main/media_kit_test/lib/tests/06.paint_first_frame.dart#L55), there currently does not seem to be a way to know whether the first frame of the video is loaded.

However, I think this would be important, if possible. The usecase is the following:

I have single videos that load into players with single video playlists. 
While the video is being loaded, I can display the thumbnail of the video myself, as it is available to me from my API and already cached. 
Previously, I used the [`video_player`](https://pub.dev/packages/video_player) package, which provides the boolean `isInitialized` with which this can be accomplished. 

I cannot seem to find an equivalent to this functionality here. The state of whether the first frame is loaded or not is not exposed anywhere. Awaiting the `VideoController.create` call does not yield this behaviour. It can be mitigated by doing something like this:

```dart
await VideoController.create(player).then((value) => Future.delayed(const Duration(milliseconds: 500), () => value));
```

which will at least prevent flickering between a thumbnail and the video player itself, but there is no guarantee for the first frame to be actually loaded after the given duration. This is also very inconvenient if the video is already loaded, as we are adding artifical delay.

**Comment by clragon** [comment]
I think it might be even nicer for my usecase if `VideoController`'s creation was not a Future, and it would instead work like a `VideoPlayer` from `video_player`, meaning, the initialization would be done inside of the `Video` widget, and whether the controller is initialized is indicated by a boolean. This would also make migration a bit easier. 

Right now, because I have to await the creation of the `VideoController`, I _have_ to display something else for at least a single Frame. This clashes when I have two routes which connect their Videos through a `Hero`, as already loaded videos will disappear for a frame during transition. 

I have no idea if this is possible the way the internals of this package work. 
I am also not sure if the `Video` widget would actually benefit from this and would be able to display already loaded videos on the first frame.

**Comment by alexmercerind** [comment]
Hi!

First of all, thanks for sponsoring me, please don't consider it a liability & don't hesitate to cancel it when you do. I appreciate your support. I had few exams last week & then fell ill, couldn't sit or walk. Now I'm back, I'm doing it.


>  think it might be even nicer for my usecase if VideoController's creation was not a Future, and it would instead work like a `VideoPlayer` from `video_player`.


One API that I can think of is:

```dart
late final player = Player();
late final controller = VideoController(player, enableHardwareAcceleration: true);
```

Since, most people keep these as attribute inside their `StatefulWidget`, adding late is necessary, but it will eliminate `async`/`await`/`Future.microtask` etc. etc.

**Comment by clragon** [comment]
You are welcome. I am just a student, so I can only donate one-time, but I believe that this is a very important package. 

Its performance, from my testing, is incrdedible and it actually encompasses the desktop platforms. 
The flutter ecosystem needs good video playing like this. 

My ideal of the usage would look something like this:

```dart

class PostVideoWidget extends StatefulWidget {
  const PostVideoWidget({required this.post, required this.player});

  final Post post;
  final Player player;

  @override
  State<PostVideoWidget> createState() => _PostVideoWidgetState();
}

class _PostVideoWidgetState extends State<PostVideoWidget> {
  late final VideoController controller = VideoController(widget.player);
  
  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
  
  @override
  Widget build(BuildContext context) {
    if (!widget.player.state.initialized) {
      return PostThumbnail(widget.post);
    }
    return AspectRatio(
      aspectRatio: widget.post.width / widget.post.height,
      child: Video(
        controller: controller,
        fill: Colors.transparent,
      ),
    );
  }
}
```

or even:

```dart
class PostVideoWidget extends StatelessWidget {
  const PostVideoWidget({required this.post, required this.player});

  final Post post;
  final Player player;

  @override
  Widget build(BuildContext context) {
    if (!player.state.initialized) {
      return PostThumbnail(post);
    }
    return AspectRatio(
      aspectRatio: post.width / post.height,
      child: Video(
        player: player,
        fill: Colors.transparent,
      ),
    );
  }
}
```

Where I do not have to create a `VideoController` at all, as I do not require its options. 
I still think it might be useful to be able to pass a `VideoController` _sometimes_, so maybe there could be two constructors for `Video`.

**Comment by alexmercerind** [comment]
I added this `VideoController.waitUntilFirstFrameRendered`:

https://github.com/alexmercerind/media_kit/blob/69f5dafc8e46b55d49dd0223c0abf08fb64135ec/media_kit_test/lib/tests/06.paint_first_frame.dart#L52
The `Future` will be completed when first frame is painted, `await` or `then`-clause may be used to get notified.

Kind of similar to: https://api.flutter.dev/flutter/widgets/WidgetsBinding/waitUntilFirstFrameRasterized.html

**Comment by alexmercerind** [comment]
> One API that I can think of is:
> 
> ```dart
> late final player = Player();
> late final controller = VideoController(player, enableHardwareAcceleration: true);
> ```

Just for clarification: I proposed the snippet above to eliminate the current async `VideoController.create` API.

**Comment by clragon** [comment]
`VideoController.waitUntilFirstFrameRendered` looks good, but I cant access it snychronously.

In my code, I have a Provider which manages my `VideoPlayer` controllers from `video_player`. 
I can access and connect them to my Widgets and if `isInitialized` is true, I can display them immediately, meaning I can transition them in a `Hero` widget between pages, with no placeholder being shown. 

When switching to `media_kit`, I have replaced my `VideoPlayer` with `Player`, so now `Player` is shared across pages.
This works fine because the video is initialized basically immediately, but it is not initialized on the same frame, meaning, on at least one frame between Route transitions, the placeholder will flicker, because we are switching to a new `VideoController`. 

I could add the `VideoController` to my Provider so that both `Player` and `VideoController` are stored there, but if I decide whether to show the placeholder based on the `waitUntilFirstFrameRendered` future, then I will still have a one frame flickering.

This is the very special problem with Futures and rendering in Flutter, and why `SynchronousFuture` (evil black magic) exists. 
I dont know if a `VideoController` can be initialized synchronously if a `Player` is already loaded. I would assume not, there is probably platform channel calls which are async and cannot be synchronous.

In that case I could store the `VideoController` accross Routes, but then I would still need to synchronously know whether it is already initialized, as waiting for `waitUntilFirstFrameRendered` will result in me showing the Placeholder for at least one frame.

**Comment by alexmercerind** [comment]
The latest update adds the `VideoController.waitUntilFirstFrameRendered` API.

On the other hand, a large dependency on async/await has been eliminated. It's now easier to use the package:

```dart
import 'package:flutter/material.dart';

import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MediaKit.ensureInitialized();
  runApp(
    const MaterialApp(
      home: MyScreen(),
    ),
  );
}

class MyScreen extends StatefulWidget {
  const MyScreen({Key? key}) : super(key: key);
  @override
  State<MyScreen> createState() => MyScreenState();
}

class MyScreenState extends State<MyScreen> {
  late final player = Player();
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    player.open(Media('https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4'));
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Video(
        controller: controller,
      ),
    );
  }
}
```

<hr>

You may provide us further feedback & express your feelings about the changes above at our [Discord](https://discord.gg/h7qf2R9n57).
Conversation here on GitHub appears to be more formal.

**Comment by alexmercerind** [comment]
> I would still need to synchronously know whether it is already initialized.

From what I can say, something like following will give you ability to tell if first frame has been rendered or not (synchronously):

```dart
final isFirstFrameRendered = (player.state.width ?? 0) > 0 && (player.state.height ?? 0) > 0;
```

**Comment by clragon** [comment]
I see.
I have opted for a different solution:

```dart
class VideoPlayer extends Player {
  VideoPlayer() {
    _initialized = controller.waitUntilFirstFrameRendered;
    _initialized.then((_) => _isInitialized = true);
  }

  late final VideoController _controller = VideoController(this);
  VideoController get controller => _controller;

  late final Future<void> _initialized;
  Future<void> get initialized => _initialized;

  late bool _isInitialized = false;
  bool get isInitialized => _isInitialized;
}
```

It's not pretty, but it works and I have no 1-frame placeholders.
I would've made wrapper objects for `PlayerState` and `PlayerStreams`, but they are not exposed so I cant do that.
(I also cant destructure them with dart 3, because of that...)

Thank you for your help.
