### ISSUE TITLE
Very large framework footprint

### ISSUE THREAD

**Issue by theolundqvist** [alexmercerind/media_kit#173]
disclaimer: This can potentially by a problem on my part.

The windows app is 44 MB
The mac app is 150 MB, of which a large part is eaten by videocodecs 
![image](https://user-images.githubusercontent.com/31588188/235584392-0af4d725-bcc9-4cc1-8b06-43746239a892.png)

Another reeeally wierd issue that I can't blame you for is that when I run `cp -r build/x.app release/x.app` the file size goes from 150 MB to 440 MB which makes me wanna throw up.

Why is the mac app so much larger than windows? My app only ever plays one single video (mp4), can I throw out some of the codecs? I used dart_vlc before, I have a feeling that avcodec can be a relic from that.

I would appreciate any help on this issue.

**Comment by alexmercerind** [comment]
It's actually a good bundle size, what else do you expect?

Having a decent video codec support with a ≤ 40 MB bundle size is nice.

Take Telegram desktop or Google Chrome as an example. Installers of these applications weigh around 60 MB. After installation, about 150 MB is occupied. It's the standard.

**Comment by birros** [comment]
Use `cp -R` instead of `cp -r` to copy symlinks.

**Comment by birros** [comment]
Also, don’t forget that libs are universal on macOS, including `x86_64` and `arm64` archs.

**Comment by theolundqvist** [comment]
Thanks for the quick response, I guess that answers my question.

Using cp -R to copy symlinks to I external libraries? Wont that break if I upload it?

**Comment by theolundqvist** [comment]
@alexmercerind 
You stated that media_kit was ["small size"](https://github.com/alexmercerind/dart_vlc/issues/254#issuecomment-1521436635) so i did not think I would go from 48 MB on mac to 150 MB by switching from dart_vlc

**Comment by birros** [comment]
> The mac app is 150 MB

The `media_kit` libs take up 75 MB uncompressed, gzipped only 29 MB.
For comparison, the [IINA](https://github.com/iina/iina) application takes up 160 MB.

> Using cp -R to copy symlinks to external libraries? Wont that break if I upload it?

I don't think so, the symbolic links are stored in a dmg. Some people already upload their application to the macOS App Store.

> Still, can I throw out any of the codecs?

The codecs are selected at build time, if you want video libs with fewer codecs you will have to compile the libs yourself: [media-kit/libmpv-darwin-build](https://github.com/media-kit/libmpv-darwin-build).
Then fork `media_kit_libs_video_macos` and override your `pubspec.yaml`.
Good Luck! ^^

**Comment by HankG** [comment]
> Thanks for the quick response, I guess that answers my question.
> 
> Using cp -R to copy symlinks to external libraries? Wont that break if I upload it?
> 
> Still, can I throw out any of the codecs?

For actual deployment you'll want to go through the XCode archiving and signing process to create a redistributable app even if you aren't distributing through the app store. For my app that brings in all the media_kit libraries (along with many many others) my download size for the macOS version is 55.3 MB and my install size is 142 MB.
