### ISSUE TITLE
[Question] How to add arguments to mpv?

### ISSUE THREAD

**Issue by tupats** [alexmercerind/media_kit#175]
I would like to use this lib to stream my camera, unfortunately I get this error: 
`flutter: Log: PlayerLog(prefix: cplayer, level: error, text: Failed to recognize file format.)
`

Solution: 
https://github.com/mpv-player/mpv/issues/4845
Adding a `--rtsp-transport=udp` to mpv arguments should solve it.

How could I do that?

Great library by the way, succesfuly using in my other app, will surely overtake all the other video libs.

**Comment by solsticedhiver** [comment]
For now, you pass argument to the libmpv backend, by using something like:

```dart
if (player.platform is libmpvPlayer) { 
   (player.platform as libmpvPlayer).setProperty("rtsp-transport", "udp"); 
 } 
```

This could change in the near future though, when 1.0.0 is released

**Comment by birros** [comment]
@tupats Can you confirm that the snippet provided by @solsticedhiver was useful to you, please?

**Comment by tupats** [comment]
I can confirm that it worked, thanks!
