### ISSUE TITLE
[Linux/BUG Report] fatal error: 'mpv/render.h' file not found

### ISSUE THREAD

**Issue by nervtech** [alexmercerind/media_kit#177]
Error occurs in  media_kit_video

- mpv version 0.27.2
- libmpv-dev version 0.27.2-1ubuntu1
- flutter version 3.7.12
- media_kit version 0.0.7+1
- media_kit_video version 0.0.9
- OS: Linux/Ubuntu 18

Error Details:
![image](https://user-images.githubusercontent.com/16267115/236619647-229b753d-b30e-4b04-882c-ee0299190e94.png)

My local libmpv dir shows:
![image](https://user-images.githubusercontent.com/16267115/236619703-5b97cc86-769a-4d36-b9db-1b25cf4a8c49.png)

**Comment by solsticedhiver** [comment]
I had the problem too. I guess you are using a too old [lib]mpv version.

I was said 

> I recommend 0.33.x or higher.

about the libmpv version

**Comment by birros** [comment]
I confirm what @solsticedhiver said, we do not intend to support an obsolete version of Ubuntu, you have two options:
- upgrade Ubuntu to a newer LTS version
- manually upgrade mpv to >= `0.33.*`

Good luck!
