### ISSUE TITLE
 Software crashes on linux

### ISSUE THREAD

**Issue by 1056824847** [alexmercerind/media_kit#179]
<img width="802" alt="image" src="https://user-images.githubusercontent.com/44287872/236724271-d37ab376-f196-4183-b20a-131d512f9e54.png">

**When enableHardwareAcceleration is false, the software will crash**

**Comment by alexmercerind** [comment]
Use new distro.

**Comment by alexmercerind** [comment]
I can't control which version of libmpv YOU install on GNU/Linux. If it doesn't have `MPV_RENDER_API_TYPE_SW`, it won't work!

**Comment by 1056824847** [comment]
> I can't control which version of libmpv YOU install on GNU/Linux. If it doesn't have `MPV_RENDER_API_TYPE_SW`, it won't work!

How not to use hardware acceleration? Because I found that some old computers have problems with hardware acceleration turned on.
