### ISSUE TITLE
media_kit,多窗口问题

### ISSUE THREAD

**Issue by ZG-123** [alexmercerind/media_kit#182]
Unhandled Exception: MissingPluginException(No implementation found for method VideoOutputManager.Create on channel com.alexmercerind/media_kit_video)，
报的是上面的错误，我目前碰到的多窗口管理问题，目前有两个窗口。在第一个窗口使用插件media_kit，完全没问题，新建窗口的以后，在第二个窗口使用的话，就会报找不到VideoOutputManager.Create这个方法，我想着这可能是插件在第二个窗口注册的问题，但是我不知道怎么办，这个要怎么解决，有人碰到过吗

**Comment by JGNS** [comment]
> 问题已经解决


请问如何解决的？

**Comment by molihuan** [comment]
> 问题已经解决

请问是如何解决的，我想参考参考，救命阿，大佬，我快疯了

**Comment by ZG-123** [comment]
需要在各个平台单独注册，https://www.jianshu.com/p/7352bff7aad9

**Comment by molihuan** [comment]
> 需要在各个平台单独注册，https://www.jianshu.com/p/7352bff7aad9

昨天已经写完了
