### ISSUE TITLE
flutter, media_kit broadcast rtsp, an occasional green screen problem? I don't know if you've seen this before

### ISSUE THREAD

**Issue by ZG-123** [alexmercerind/media_kit#183]
flutter, media_kit broadcast rtsp, an occasional green screen problem? I don't know if you've seen this before

**Comment by alexmercerind** [comment]
I haven't seen this before. Also, please reproduce the bug in test application first. Atleast, share the media sample for us to work.

**Comment by ZG-123** [comment]
It happens once in a while. It could be my code
