### ISSUE TITLE
[Question] How to fix HDR "white saturation"

### ISSUE THREAD

**Issue by birros** [alexmercerind/media_kit#184]
Some HDR video files may have color aberration, for example "white saturation":

<img width="1440" alt="screenshot_hdr_macos" src="https://github.com/alexmercerind/media_kit/assets/32417752/ca9d27f7-6f35-41ba-a5e3-6098ea43702a" />

From left to right on the screenshot:
1. `mpv --hwdec=auto video.mov`
2. `mpv --hwdec=auto --tone-mapping=linear video.mov`
3. `mpv --hwdec=auto --tone-mapping=hable video.mov`
4. `open -a "QuickTime Player" video.mov`

In my opinion, 3. is the closest to QuickTime: `mpv --hwdec=auto --tone-mapping=hable video.mov`
But 2. may be closer to reality: `mpv --hwdec=auto --tone-mapping=linear video.mov`

<details>
<summary>Attachments</summary>
<a href="https://github.com/alexmercerind/media_kit/assets/32417752/7fa8e003-71ca-4919-b2f4-e9370d16ff58">video.mov</a>
</details>

**Comment by hongfeiyucode** [comment]
How did you solve this problem in media-kit? Thank you very much
