### ISSUE TITLE
[Bug Report] Cannot seek in long network videos

### ISSUE THREAD

**Issue by chaeMil** [alexmercerind/media_kit#186]
First, thanks for the awesome work!

The problem arises when you play long network video. Seeking in the video is not working it just continues to play. 

`Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E772610a darwin-x64, locale en-GB)`

**Comment by birros** [comment]
Can you provide more information:
- Do you have the same behavior with `media_kit_test`?
- What size / length is the video stream?
- What format / codec the video stream use?
- Does the server distributing the video stream support seeking? (e.g. [206 Partial Content](https://developer.mozilla.org/fr/docs/Web/HTTP/Status/206)...)

**Comment by chaeMil** [comment]
- `media_kit_test` behave correctly no issues there
- Video is streamed from google apis photos library so whethever that gives

will get more info when i get to it.

**Comment by birros** [comment]
> `media_kit_test` behave correctly no issues there

Copy the `SeekBar` from `media_kit_test` into your app, your problem might be a bad implementation in your UI.

**Comment by alexmercerind** [comment]
Bug in your code then.
