### ISSUE TITLE
Using the demo provided doesn't work on window11, please help me

### ISSUE THREAD

**Issue by lingg4556** [alexmercerind/media_kit#191]
media_kit: ^0.0.7+1
  media_kit_video: ^0.0.9
  media_kit_native_event_loop: ^1.0.3
  media_kit_libs_windows_video: ^1.0.2
  media_kit_libs_windows_audio: ^1.0.3

import 'package:flutter/material.dart';

import 'package:media_kit/media_kit.dart';                        /// Provides [Player], [Media], [Playlist] etc.
import 'package:media_kit_video/media_kit_video.dart';            /// Provides [VideoController] & [Video] etc.

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MediaKit.ensureInitialized();
  runApp(
    const MaterialApp(
      home: MyScreen(),
    ),
  );
}

class MyScreen extends StatefulWidget {
  const MyScreen({Key? key}) : super(key: key);
  @override
  State<MyScreen> createState() => MyScreenState();
}

class MyScreenState extends State<MyScreen> {
  /// Create a [Player].
  final Player player = Player();
  /// Store reference to the [VideoController].
  VideoController? controller;

  @override
  void initState() {
    super.initState();
    Future.microtask(() async {
      /// Create a [VideoController] to show video output of the [Player].
      /// Play any media source.
      await player.add(Media('https://spbtest.oss-ap-southeast-3.aliyuncs.com/temp/video/16216306831720448/u/20230512/29212855827955712/47486196154658816.mp4'));
      controller = await VideoController.create(player);

      // player.play();
      //
      setState(() {});
    });
    player.streams.playlist.listen((e) => print("playlist:$e"));
    player.streams.playing.listen((e) => print("playing:$e"));
    player.streams.completed.listen((e) => print("completed:$e"));
    player.streams.position.listen((e) => print("position:$e"));
    player.streams.duration.listen((e) => print("duration:$e"));
    player.streams.volume.listen((e) => print("volume:$e"));
    player.streams.rate.listen((e) => print("rate:$e"));
    player.streams.pitch.listen((e) => print("pitch:$e"));
    player.streams.buffering.listen((e) => print("buffering:$e"));
  }

  @override
  void dispose() {
    Future.microtask(() async {
      /// Release allocated resources back to the system.
      await controller?.dispose();
      await player.dispose();
    });
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    /// Use [Video] widget to display the output.
    return Container(
      width: 800,
      height: 800,
      child: Column(
        children: [
          ElevatedButton(
              onPressed: () async {
                await player.play();
                setState(() {});
              },
              child: Text("Play")),
          Video(
            /// Pass the [controller].
            width: 600,
            height: 600,
            controller: controller,
          ),
        ],
      ),
    );
  }
}

**Comment by solsticedhiver** [comment]
Please format correctly the code you provide with 'Add code' from the toolbar.
What is the error you got if any?

Have you tried the *media_kit_test* example from that same directory in media_kit github source code project?

**Comment by alexmercerind** [comment]
I never understood what's "doesn't work", are you even a developer? Is it:
- Not compiling
- Throwing exception
- Crashing on runtime

??? what?

Secondly, run our test application first, there's a direct URL. If that runs, it's your & your code's own fault.
