### ISSUE TITLE
[Question] Get current frame image

### ISSUE THREAD

**Issue by renatomotorline** [alexmercerind/media_kit#192]
Hi,

I'm using the media kit to show RTSP streams, and I want to save some frames of the camera to use as thumbnails for the next time the user access it, is possible to get/capture the current frame?

Thanks.

**Comment by Quackdoc** [comment]
to do this, we could probably call MPV's screenshot functionality. im not sure how it would be best to implement however.

**Comment by Quackdoc** [comment]
I see a couple ways of doing this, the first would be simple grabbing the frame and encoding it, this is probably the best way to do it, however another method for supported platforms would be to use MPV's screenshot feature, this could also allow supporting a variety of formats to save the image as assuming mpv is built with support for them jpg, png, jxl, webp)

**Comment by alexmercerind** [comment]
I use the `screenshot-to-file` command in my private project; works very well. No public screenshot API yet unfortunately.

**Comment by renatomotorline** [comment]
I'm using the [screenshot](https://pub.dev/packages/screenshot) package.

**Comment by deckerst** [comment]
@renatomotorline with that kind of package you would grab the widget rendering, so it would be at whatever resolution it appears on your device, not the original video resolution.

**Comment by alexmercerind** [comment]
Hi!

A new `screenshot` method has been added, which returns the video snapshot as `Uint8List`.

Docs: https://github.com/alexmercerind/media_kit#capture-screenshot

Please refer to the ["Installation" section of the README](https://github.com/alexmercerind/media_kit#installation) to update.

Thanks!
