### ISSUE TITLE
[Bug Report][Windows] Incorrect duration stream when playing webm files from local storage

### ISSUE THREAD

**Issue by akaMrNagar** [alexmercerind/media_kit#195]
Problem :
When i tried playing locally stored webm file the player is treating it as a online stream and the event stream of duration is 1-3 seconds ahead of the position stream. It is not displaying the total duration of the media. This is only happening while playing webm files.

Solutions Tried :
I also tried changing the buffer size.

ps: let me know if screenshot is needed.

**Comment by akaMrNagar** [comment]
![Screenshot](https://github.com/alexmercerind/media_kit/assets/80568442/dd424d39-2239-4bb0-be5c-3baa9fc3e8a2)

Screenshot to help...

**Comment by alexmercerind** [comment]
Working as intended. That's how media streaming & demuxer works.

**Comment by akaMrNagar** [comment]
> Working as intended. That's how media streaming & demuxer works.

Just want to clear that i am not streaming through url, i am playing the downloaded media,
but vlc shows the full duration of the media while playing.
