### ISSUE TITLE
[Enhancement] Video rotation

### ISSUE THREAD

**Issue by zedmyls** [alexmercerind/media_kit#196]
Hi,
I encountered an issue while using your plugin and I couldn't solve it.
I'm running your sample program on macOS platform and I added steams.height.listen and steams.width.listen to play a local video file. Here's the problem: when the video is 1280*720, steams.height.listen and steams.width.listen correctly print the height and width of the video. However, when the video is 720*1280, steams.height.listen prints 720 and steams.width.listen prints 1280, which is reversed.
I hope you can address this issue and provide me with an explanation or a solution. Thank you so much. Please forgive any mistakes in my English, as it is not my native language and I used a translation engine for this paragraph.

**Comment by alexmercerind** [comment]
AFAIK you're using `.mov` format. Generally, it applies orientation as a video filter based on metadata.

**Comment by birros** [comment]
It may be possible to block the rotation with `--video-rotate=no` as the mpv doc suggests.

https://mpv.io/manual/stable/#options-video-rotate

> --video-rotate=<0-359|no>
> Rotate the video clockwise, in degrees. If no is given, the video is never rotated, even if the file has rotation metadata. (The rotation value is added to the rotation metadata, which means the value 0 would rotate the video according to the rotation metadata.)
>
> When using hardware decoding without copy-back, only 90° steps work, while software decoding and hardware decoding methods that copy the video back to system memory support all values between 0 and 359.

@zedmyls can you try this with mpv directly please.

**Comment by zedmyls** [comment]
@birros ,thank you so much.I will try.

**Comment by deckerst** [comment]
How can I pass the `--video-rotate=no` option with media_kit?

**Comment by alexmercerind** [comment]
Hi,

We generally keep issues open until the next stable release.

**Comment by alexmercerind** [comment]
Hi!


Please refer to the ["Installation" section of the README](https://github.com/alexmercerind/media_kit#installation) to update.

Thanks!

**Comment by kchasiotis** [comment]
@alexmercerind could you point me to a way to rotate a vertical video. I cannot seem to find it in the README.
