### ISSUE TITLE
Buffering for m3u8 frames

### ISSUE THREAD

**Issue by BrunoC96** [alexmercerind/media_kit#200]
Hi,

I try to use the player with a stream of .ts frame, that I pick from a m3u8 file, and put it in a Playlist, but I have a problem. 
Each time the player go to the next frame, there is some delay for loading it. So because the frame are 6 second long, each 6 second I have a small interrupt that is so annoying to see.

There is a way to buffer the next frame, before the end of the current one, so there is no more delays??

Thanks in advance, for the response.

**Comment by alexmercerind** [comment]
You can enable [`--prefetch-playlist`](https://mpv.io/manual/stable/#options-prefetch-playlist) maybe.

Why not create separate `Player`s if you need that much control in your hand? Definitely an out of scope for us.

**Comment by alexmercerind** [comment]
Other plugins don't even offer a dedicated playlist feature; & we are not even 1.0.0 yet. What do you expect?

**Comment by BrunoC96** [comment]
Thanks for the response,

I was just asking if there was a solution to my problem, because I was trying to do same video & audio frame manipulation with AI, and after that I need to putting them back together as a single video stream.

I try to see if with --prefetch-playlist it will work.

Thanks again for your response and your time.
