### ISSUE TITLE
Can't build on Arch Linux

### ISSUE THREAD

**Issue by 0Franky** [alexmercerind/media_kit#203]
Hi @alexmercerind,
first of all thank you for your contribution!

I have a problem launching the sample package (media_kit_test).
I uploaded the log file where the errors that come out are reported.
I tried searching on the internet but I can't figure out what the problem could be.

[log mediakit.txt](https://github.com/alexmercerind/media_kit/files/11542211/log.mediakit.txt)

I installed this packages:
- https://archlinux.org/packages/extra/x86_64/mpv/
- https://github.com/mpv-player/mpv-build

Can you help me?

Thank you in advance!

**Comment by solsticedhiver** [comment]
This is not clear what version of mpv you have installed.
You say you have th empv package from arhclinux installed, so what about mpv-build?

*mpv-build* is a script to build mpv from git source on github. It does not give an archlinux package.

Did you install mpv with *mpv-build*, aka with `sudo ./install` in mpv-build directory?
What is the point given the mpv arhclinux package is fairly recent?

Finally, this is more help that you are requesting, than about an issue. Better use the discord room at https://discord.gg/h7qf2R9n57

**Comment by solsticedhiver** [comment]
And I have no problem building and running the media_kit_test app on archlinux, with flutter 3.10.1 and mpv-1:0.35.1-6

**Comment by alexmercerind** [comment]
It's entirely an issue on your development machine. Something I can't help with (& I'm not obliged) either.

As mentioned by @ solsticedhiver, they are able to build & run the project just fine.

I can't help or correct things which aren't in my hand. It's your installation of GNU/Linux; you are responsible.
