### ISSUE TITLE
[Question] How to add an audio equalizer

### ISSUE THREAD

**Issue by coolight7** [alexmercerind/media_kit#205]
Hello, 
* I had some issues when append a EQ for audio.
* I had try this code, but it not work:
```
_player.setProperty(
      "af",
      "lavfi=[firequalizer=gain_entry='entry(1000,20);entry(2000,20);entry(4000,10)']",
);
```
* after that, there are some error on console:
```
ffmpeg","msg":["error","AVFilterGraph: No such filter: 'firequalizer'"]
ffmpeg","msg":["error","AVFilterGraph: Error creating filters"]
user_filter_wrapper","msg":["error","Creating filter 'lavfi' failed."]
cplayer","msg":["error","Audio filter initialized failed!"]
```
* If change the property("af") to "af-add" or "af-append", it will no error output. But also not work.
* Sorry, my English is so poor.
* Thanks to anybody who replies.

**Comment by coolight7** [comment]
There are some infomation about mpv audio EQ :
* --af=lavfi
  * https://mpv.io/manual/master/#audio-filters-af
* mpv player add the firequalizer :
  * https://github.com/mpv-player/mpv/issues/9979#issuecomment-1068338756

**Comment by alexmercerind** [comment]
There's literally a filter named "equalizer" which you are meant to use. We've enabled it in our builds.

**Comment by coolight7** [comment]
> There's literally a filter named "equalizer" which you are meant to use. We've enabled it in our builds.
Thanks, it is working as well !

**Comment by DemeoStep** [comment]
> > There's literally a filter named "equalizer" which you are meant to use. We've enabled it in our builds.
> 
> Thanks, it is working as well !

Can you show final solution?

**Comment by coolight7** [comment]
> Can you show final solution?

* "equalizer" is from ffmpeg:
* [8.86.1 Examples](http://ffmpeg.org/ffmpeg-filters.html#toc-Examples-24)

* you can use it such as:
```
class MyEQConfigItem_c {
  double centerFrequency;
  double gain;
  double width;
  String width_type;

  MyEQConfigItem_c({
    this.centerFrequency = 0,
    this.gain = 0,
    this.width = 200,
    this.width_type = "h",
  });
}

  void setEQList(List<MyEQConfigItem_c> list) {
    String restr = "";
    for (int i = 0; i < list.length; ++i) {
        if (restr.isNotEmpty) {
          restr += ",";
        }
        restr +=
            "equalizer=f=${list[i].centerFrequency.toStringAsFixed(2)}:g=${list[i].gain.toStringAsFixed(2)}";
      }
    if (mkPlayer.platform is libmk.NativePlayer) {
      (mkPlayer.platform as libmk.NativePlayer)
          .setProperty(
        "af",
        restr,
      );
    }
  }
```
* `mkPlayer` is media_kit.Player()

**Comment by DemeoStep** [comment]
Tnx. Working with mp3, but it not working with FLAC. 
But
`mpv 'Def Leppard.flac' -af=equalizer=f=5500:t=h:w=200:g=16`
works

**Comment by DemeoStep** [comment]
tracing mpv log revealed this error
`flutter: PlayerLog(prefix: ffmpeg, level: debug, text: mpv_src_default_in: tb:1/44100 samplefmt:s16 samplerate:44100 chlayout:stereo)
**flutter: PlayerLog(prefix: ffmpeg, level: error, text: 'aresample' filter not present, cannot convert formats.)**
flutter: PlayerLog(prefix: lavfi, level: fatal, text: failed to configure the filter graph)
flutter: PlayerLog(prefix: af, level: error, text: Disabling filter equalizer.00 because it has failed.)`

**Comment by coolight7** [comment]
> tracing mpv log revealed this error

yea, some time it has so mary warns or error in console with flac

* but I don't know anything about it, i have no idea to resolve.
* I am trying other filter, but media_kit's libmpv does not contain another eq filter. So i modify `media_kit_libs_android_video/android/build.gradle` to replace `libmpv.so`. 
* And Then we can try other eq filter, such as firequalizer.
* if you want to know what the libmpv.so support:
```
af=help
```

**Comment by eben-ezeer** [comment]
did you actually find how to make it work with flac, also not working with wav
