### ISSUE TITLE
[Enhancement] AirPlay support

### ISSUE THREAD

**Issue by calebvetter** [alexmercerind/media_kit#207]
When casting a video to AirPlay, only the audio is sent while the video remains on the device. I'm assuming this is because media_kit renders the actual image of the video on its own instead of using Apple's AVPlayer class? If that's the case, support for AirPlay may need to be something built into the media_kit package if it's ever going to work properly, possibly switching between custom rendering and AVPlayer when AirPlay is active.

**Comment by calebvetter** [comment]
Didn't mean to sound confident at all 😅. Mearly trying to provide as much information/observation as possible.

Also, it appears I was wrong in that AVPlayer isn't the only way to stream AirPlay content to external devices. It looks like there's an alternate way to stream pre-rendered frames:
https://developer.apple.com/documentation/avfoundation/streaming_and_airplay/implementing_flexible_enhanced_buffering_for_your_content

Again, I know mostly nothing, haha. Just hoping some of this is relevant for implementing AirPlay in media_kit. I love this project and where it's headed. It would be amazing to have AirPlay as well as Chromecast built into media_kit.

**Comment by birros** [comment]
Maybe the code for AirPlay support will be similar to what @23doors did for iOS PIP support #206, it's something to explore.

**Comment by birros** [comment]
Well, after reflection, it seems impossible in the near future.
As a proof, even IINA can't implement it for 6 years!!!
See: https://github.com/iina/iina/issues/63

**Comment by alexmercerind** [comment]
I finally had time to analyze this issue.

This is completely irrelevant. Chromecast, AirPlay etc. take a complete file source & just stream it themselves. It has nothing to do with video rendering, playback, decoding etc. The package:media_kit is made to play video & audio inside the application. If you're aiming to AirPlay; a better approach will be to have a separate package.

**Comment by alexmercerind** [comment]
If this ever gets worked on in future; it will be part of separate package.
