### ISSUE TITLE
[Bug Report] video streaming with rtsp not working

### ISSUE THREAD

**Issue by NitinITCH** [alexmercerind/media_kit#214]
**Hi, I,m working with IP camera and get video streaming through RTSP url using media_kit library but get no response and error.**

It appears on console.

Intel(R) HD Graphics 5500
media_kit: ANGLESurfaceManager: Direct3D Feature Level: 11_0
1 1
media_kit: VideoOutput: Create Texture: 2960304571456
media_kit: VideoOutput: Using H/W rendering.
1920 1080
media_kit: VideoOutput: Free Texture: 2960304571456
media_kit: ANGLESurfaceManager: Direct3D Feature Level: 11_0
media_kit: VideoOutput: Create Texture: 2960304165472
flutter: VideoOutput.Resize
flutter: {handle: 2959983853344, id: 2960304571456, rect: {height: 1080, left: 0, top: 0, width: 1920}}
flutter: VideoController: Texture ID: 2960304571456
flutter: VideoOutput.Resize
flutter: {handle: 2959983853344, id: 2960304165472, rect: {height: 1080, left: 0, top: 0, width: 1920}}

**Comment by alexmercerind** [comment]
Not enough details for me to say anything.

**Comment by alexmercerind** [comment]
https://github.com/bluecherrydvr/unity uses package:media_kit for playback of RTSP streams.

Something is wrong on your end; not mine.

**Comment by ZG-123** [comment]
Have you solved your problem yet? Please list the code so I can look at it
