### ISSUE TITLE
How to get the length of the video from Player or Controller?

### ISSUE THREAD

**Issue by chyiiiiiiiiiiii** [alexmercerind/media_kit#224]

**Comment by alexmercerind** [comment]
You can access the duration of the currently playing `Media` using `Player.state.duration` or `Player.streams.duration`.

You can [refer to our example application](https://github.com/alexmercerind/media_kit/tree/main/media_kit_test) for code samples & other usage examples. 

Close the issue if you feel your question has been answered.

**Comment by chyiiiiiiiiiiii** [comment]
@alexmercerind  Thanks for your response.
