### ISSUE TITLE
[Question] Clearkey DRM implementation

### ISSUE THREAD

**Issue by asbansal** [alexmercerind/media_kit#229]
Hi, is it possible to play clearkey encrypted videos in windows?

**Comment by alexmercerind** [comment]
I don't know what that is & neither I have any interest in adding it; at-least before 1.0.0.

**Comment by asbansal** [comment]
Appreciate the quick response @alexmercerind . 

I actually wanted to play encrypted videos in my app (i sell paid courses). I think the reason you haven't come across this is absence of DRM implementation in libmpv (which is being used in windows here).

Some popular players actually have this, like [exoplayer](https://developer.android.com/guide/topics/media/exoplayer/drm) , dash.js, video.js etc.

Nevertheless, this might be worth exploring when media_kit package is more popular (which I'm sure it will be).

Thanks
