### ISSUE TITLE
[Bug Report] OSD progress bar from libmpv is not hidden on Windows

### ISSUE THREAD

**Issue by bdlukaa** [alexmercerind/media_kit#23]
This progress bar is displayed in the middle of the `Video` widget when `seek` is called. It just appears for a brief second and disappear as soon as seeking is completed.

![image](https://user-images.githubusercontent.com/45696119/212749719-67402bc6-12e5-48ba-8194-60099b44bc74.png)

**Comment by Quackdoc** [comment]
temporary solution would be to use `.setProperty("osd", "no")` (you can see an example for this [here ](https://github.com/alexmercerind/media_kit/blob/a08cd91594e5bbe3a60fcfabf7d087fa9f405311/media_kit_test/lib/main.dart#L375)

but this is probably something we should disable.

**Comment by alexmercerind** [comment]
https://github.com/alexmercerind/media_kit/blob/a08cd91594e5bbe3a60fcfabf7d087fa9f405311/media_kit/lib/src/libmpv/player.dart#L935-L945

I do set `osd-level` which should "in theory" disable every visible control.
Feel free to make it right _i.e._ expose another option in `PlayerConfiguration` or select correct one here.
