### ISSUE TITLE
[Bug Report] Uncorect sizes for 1920/1080 video

### ISSUE THREAD

**Issue by krida2000** [alexmercerind/media_kit#233]
If video has `height = 1920` and `width = 1080` its sizes will be swapped.

Logs: `{handle: 2642217035440, id: 2641921280496, rect: {height: 1080, left: 0, top: 0, width: 1920}}`

Also attach video with what you can test it.

<details>
  <summary>Video</summary>
  
https://github.com/zezo357/flutter_meedu_videoplayer/assets/71345244/d18760cd-7cd6-435e-b241-06f09b690b49
 </details>

**Comment by alexmercerind** [comment]
#196

**Comment by alexmercerind** [comment]
The video size is still 1920x1080. The viewport is rotated by 90 degree. That doesn't change the size of output/resolution.
