### ISSUE TITLE
USB external camera, video stream rtsp playback, video list full screen, exit full screen, other camera video will be black, and then continue to play.

### ISSUE THREAD

**Issue by ZG-123** [alexmercerind/media_kit#234]
Development encountered a phenomenon, I do not know whether it is a problem, Linux external multiple USB cameras, display video streaming, if I make the list of cameras full screen, and then slide to make a camera show the picture of the full screen, exit the full screen, the picture of other cameras will be black, and then normal playback. This problem is very troubling, I don't know if other people have encountered it。
After you exit the full screen, the following log is displayed:
2023-06-14 16:46:04.308 sample[56329:373021] VideoOutput: enableHardwareAcceleration: true
flutter: VideoOutput.Resize
flutter: {id: 105553133037664, handle: 140538640663472, rect: {top: 0.0, width: 0.0, height: 0.0, left: 0.0}}
flutter: NativeVideoController: Texture ID: 105553133037664
2023-06-14 16:46:07.578 sample[56329:373021] TextureGL: resize: 1024.0x576.0
flutter: VideoOutput.Resize
flutter: {rect: {left: 0.0, width: 1024.0, height: 576.0, top: 0.0}, handle: 140538640663472, id: 105553133037664}

**Comment by alexmercerind** [comment]
No code, no help. We don't even provide a full screen feature yet.

**Comment by ZG-123** [comment]
`Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(0),
      decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(GlobalConfig.paddingValue),
          color: Themes.dark.backgroundColor
      ),
      child: controller != null ? Video(
//        key: UniqueKey(),
        /// Pass the [controller].
        controller: controller!,
      ) : Container(),
    );
  }`


`ListView(
                  shrinkWrap: true,
                  controller: _controller,
                  children: cameraViewList(cameras, width, height, themeColors, isClose),
                ),`
That's the list and the code for one of the items in the list. The video plays normally, so that the window full screen, and then slide the video playlist, and then exit the full screen, through the USB connection does not appear on the screen of the video will appear black screen, in the display, is probably this phenomenon.

**Comment by ZG-123** [comment]
https://github.com/alexmercerind/media_kit/assets/14268035/5cfd0ec2-ebcf-4269-bbc0-1526c72ea1bf
