### ISSUE TITLE
does not has any example !

### ISSUE THREAD

**Issue by kiaxseventh** [alexmercerind/media_kit#238]
Thank you for developing this very efficient kit.
unfortunately, the lack of a simple, practical example makes it very difficult to use. Please make a practical example

thank you

**Comment by alexmercerind** [comment]
https://github.com/alexmercerind/media_kit#3-render-video-output is a self sufficient example.

More code samples are available at: https://github.com/alexmercerind/media_kit/tree/main/media_kit_test/lib/tests.

We're still working on the project, it's in development stage. See:
- #92 
- #114
