### ISSUE TITLE
[Question] Live HLS Stream not playing from start of stream

### ISSUE THREAD

**Issue by quidamschwarz** [alexmercerind/media_kit#247]
I have a video stream from a camera recorded via ffmpeg on some server in HLS format (m3u8), and i want to view the recording in my app - seekable from the start of the recording until the currently recorded frames.

Loading the m3u8 file into the player only loads the last couple of seconds into the player, and i am not able to seek back to the beginning of the stream - even though the m3u8 file contains all fragments and looks like

> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-TARGETDURATION:6
> #EXT-X-MEDIA-SEQUENCE:0
> #EXTINF:5.042700,
> video-00000.m4s
> #EXTINF:5.999978,
> video-00001.m4s
> #EXTINF:4.000556,
> video-00002.m4s
> #EXTINF:6.002178,
> video-00003.m4s
> ...
> (ongoing without #EXT-X-ENDLIST tag)

By contrast, i can load the same m3u8 file into VLC app and get access to the full stream, including the very beginning of the recording.

How to achieve this with media_kit player?

**Comment by alexmercerind** [comment]
How does [mpv](https://mpv.io/) work with your HLS stream?

**Comment by quidamschwarz** [comment]
I now just tested the Android app version - it is showing the same behavior: just showing the last couple of seconds back from the current end of the stream.

So this indicates that the "issue" is deeper down? Is there some configuration option for mpv to tweak the behavior?

**Comment by alexmercerind** [comment]
Does the following work?

```dart
final player = Player();

if (player.platform is libmpvPlayer) {
  await (player.platform as dynamic).setProperty(
    'demuxer-lavf-o',
    'live_start_index=0',
  );
}

await player.open(/* source */);
```

**Comment by alexmercerind** [comment]
We have this `setProperty` API exposed which allows fiddling with libmpv/FFmpeg specific properties & options.

Adding few links:

- https://mpv.io/manual/stable/)/manual/stable/
- https://ffmpeg.org/ffmpeg-formats.html#hls-1
- https://stackoverflow.com/questions/40009446/

**Comment by alexmercerind** [comment]
Please close the ticket if your problem is resolved.

**Comment by quidamschwarz** [comment]
Perfect! It is now loading from the start of the recording. 
I actually previously tried to make use of the the live_start_index flag in ffmpeg (resp. also patch the m3u8 file by hand accordingly), but nothing worked. Now, setting the property directly on the player is also fine for me.
Many thanks, in particular for the quick response, i will close this ticket.

**Comment by quidamschwarz** [comment]
All resolved. Many thanks.

**Comment by quidamschwarz** [comment]
Hi @alexmercerind , 
i need to state a follow-up question: The stream is now started from the beginning. Great, as i requested. 
But now the 'duration' property of the player only seem to reflect the already buffered snippets, and not the currently remaining available time. 
So if the recording is already 30 minutes long, the player duration still indicates only about 2.5 minutes (i guess depending on buffer size), and hence there is no chance to easily seek to minute 27 or to the end of the stream.
In principle, the information about the duration is present in the m3u8 file as given above, but i couldn't figure out some properties of mpv that would make use of that information.

Do you know a solution of this? Thanks in advance.

**Comment by alexmercerind** [comment]
I'm not very familiar with this either.

I'm sure you'll find likely find some mpv configuration that would work. Parsing m3u8 yourself doesn't look very tough either.

Sorry... I happen to be busy with a few other things in the project; not really dealing with specifics as such at the moment.

**Comment by alexmercerind** [comment]
Currently, only support is provided for the API exposed by the `Player` class.

The users are free to use the `setProperty` API & use their knowledge. I can't be sure of everything/anything done after that.

**Comment by quidamschwarz** [comment]
Ok, then i will dive deeper into mpv and in case i find a solution, i will post it here.

**Comment by alexmercerind** [comment]
A better place to talk can be our Discord. 

[![](https://img.shields.io/discord/1079685977523617792?color=33cd57&label=Discord&logo=discord&logoColor=discord)](https://discord.gg/h7qf2R9n57)
