### ISSUE TITLE
[Question] Subtitle font on Android

### ISSUE THREAD

**Issue by deckerst** [alexmercerind/media_kit#255]
I see that `media_kit_libs_android_video` bundles the `Noto Sans Regular` font as the `subfont.ttf` asset, but I'm getting tofu for any non-latin text (Chinese, Arabic, etc.) in subtitles on Android.

Should I call something to use that font? Is it supposed to be used automatically but it's somehow not working?

**Comment by alexmercerind** [comment]
Two proposals:

1. You want to keep using mpv's subtitle rendering:

The Noto Sans Regular isn't enough AFAIK. [This .ttf file from mpv-android covers a more extensive range of symbols](https://github.com/mpv-android/mpv-android/blob/master/app/src/main/assets/subfont.ttf). I propose to expose `androidSubtitleFont` in `PlayerConfiguration` (edit following line). Add the new `.ttf` file in your Flutter assets, and pass the path.

https://github.com/alexmercerind/media_kit/blob/30e19631846ac056f121b98f3ab4de768aef9c8c/media_kit/lib/src/player/libmpv/player/real.dart#L1606

2. You want to use Flutter based subtitle rendering: 

Have a look (& provide feedback) at #166.

**Comment by alexmercerind** [comment]
Both will require additional work. I'm involved with #250 & #252; can't have a look at this in near future.

**Comment by alexmercerind** [comment]
A stable version has been rolled out. A number of major enhancements.

Please refer to the ["Installation" section of the README](https://github.com/alexmercerind/media_kit#installation) to receive the update.

<hr>

For future visitors, we have now exposed two parameters in `PlayerConfiguration`:

- `libass`: Whether to use [libass](https://github.com/libass/libass) based subtitle rendering for native backend.
  By default, subtitles rendering is Flutter `Widget` based.
- `libassAndroidFont`: Asset name of the `.ttf` font file to be used for [libass](https://github.com/libass/libass) based subtitle rendering on Android.
  e.g. `assets/fonts/subtitle.ttf`

It will provide good control.

**Comment by JasperElton** [comment]
Where do I even get the subtitle.ttf asset?
