### ISSUE TITLE
[Bug Report][Linux] Pure performance on Celeron

### ISSUE THREAD

**Issue by andrew-tpz** [alexmercerind/media_kit#258]
### Case
Show one video stream on two FullHD displays.

### System
Processor: Intel Celeron J1900 (4 x 1.99 GHz)
VGA: integrated
RAM: 4 GB
Displays: 2 x 1900x1080
OS: Ubuntu 22.04.1 LTS x64

### Expectation / Reality
Smooth playback / There are Jerks.

### Visual test
I run two mpv instances (one per display) and visually they play smoother.

### Measure test
I use intel_gpu_top utility to compare GPU load.

**Two mpv instances:**
<img width="564" alt="two_mpv_instances" src="https://github.com/alexmercerind/media_kit/assets/74716417/baed5d7c-63ab-4eb5-99db-a7e3e2dbb2f5">

**media_kit:**
<img width="565" alt="media_kit_flutter" src="https://github.com/alexmercerind/media_kit/assets/74716417/73eed518-eb1e-4f0c-92b9-a8ef5cab6664">

### Demo sources

**Script to run two mpv instances:**
```
#!/bin/bash

path=~/Videos
mpv --fs --screen=0 --loop-playlist=inf $path &
mpv --fs --screen=1 --loop-playlist=inf $path
```

**Demo Flutter project**
[media_kit_duo.zip](https://github.com/alexmercerind/media_kit/files/11906309/media_kit_duo.zip)

**Comment by Quackdoc** [comment]
flutter is pretty heavy on gpu in general compared to other UI kits, when you pair that with mpv it gets really heavy, Gen7 also have really weak gpus, it also doesn't help that the intel driver for these devices really isn't that good either. 

I highly doubt any gpu heavy flutter app will be very performant on these devices until flutter manages to enable impeller + vulkan for linux, I would say this is an upstream issue more then likely

**Comment by alexmercerind** [comment]
The GTK/GDK's GL implementation is already very sluggish. https://github.com/flutter/flutter/issues/88996

At the moment, package:media_kit for GNU/Linux performs the worst.

In the latest update of Flutter, I have even noticed that two simultaneous `Video` cause second one to not use H/W at all. And... it's a regression in Flutter; nothing can be done on my end. A number of causes.

Lastly, your machine is already having 66% load in mpv while playing two videos... maybe it can play 3 videos at once. 2 videos at once + Flutter UI doesn't look that bad.

**Comment by alexmercerind** [comment]
We're certainly open to improvements & indeed there's a large scope for GNU/Linux.
