### ISSUE TITLE
Dart 3 compatibility

### ISSUE THREAD

**Issue by deckerst** [alexmercerind/media_kit#262]
Some of the dependencies of media_kit 1.0.0 are incompatible with the latest versions of other packages that moved on to Dart 3.

Specifically, `http: ^0.13.4` and `wakelock: ^0.6.2` (because of `wakelock_windows 0.2.1`) are problematic, but there may be others. For `http`, there is currently a newer version, but not yet for `wakelock` (which seems unmaintained):
- issue: https://github.com/creativecreatorormaybenot/wakelock/issues/202
- PR: https://github.com/creativecreatorormaybenot/wakelock/pull/213

It's possible for me as a consumer to work around this by adding dependency overrides in my pubspec, but it's not ideal.

**Comment by alexmercerind** [comment]
I think it's mostly the dependencies' major version changes.

The media_kit itself & package it depends upon are already Dart 3 compatible.

**Comment by alexmercerind** [comment]
I did resolve http issue. wakelock seems a real blocker.

**Comment by wizlif** [comment]
Managed to migrate to wakelock_plus https://github.com/alexmercerind/media_kit/pull/273

**Comment by alexmercerind** [comment]
Keeping issue open until next stable release.

**Comment by kirill-21** [comment]
> Keeping issue open until next stable release.

When will this be landed?

**Comment by alexmercerind** [comment]
> When will this be landed?

Today.

<hr>

Please refer to the ["Installation" section of the README](https://github.com/alexmercerind/media_kit#installation) to update.

Thanks!

<hr>

A number of major improvements have been made in this update, whether it be performance, stability or bundle-size.

#### package:media_kit
- feat: `Player.screenshot` for capturing video snapshots as `Uint8List`
- feat: external audio track & subtitle track support
  - `AudioTrack.uri`
  - `SubtitleTrack.uri` & `SubtitleTrack.data`
- feat: WebVTT subtitle support
- feat: `Player.state.videoParams` & `Player.stream.videoParams`
- feat: `Player.state.subtitle` & `Player.stream.subtitle`
- perf(android): use `hwdec=mediacodec` w/ `enableHardwareAcceleration`
- fix(android): OpenSL ES limit
- fix(android): improve stability
- fix(android): file-descriptor clean-up for content:// URI
- fix(windows): improve stability
- fix: immediately set `vid`/`aid`/`sid` to `no` in `dispose`
- perf: reduce bundle size by <= 50%
- perf: do not decode video until `VideoController` attach
#### package:media_kit_video
- feat: `SubtitleView`, `SubtitleViewConfiguration`
- feat: `shiftSubtitlesOnControlsVisibilityChange` in `MaterialVideoControls` & `MaterialDesktopVideoControls`
- feat: apply rotation from metadata to video output
- feat: improve wakelock behavior
- feat: `pauseUponEnteringBackgroundMode`
- fix: `bufferingIndicatorBuilder` padding in `MaterialVideoControls` & `MaterialDesktopVideoControls`
- fix(windows): maintain aspect ratio in s/w rendering pixel-buffer size clamping
- fix(linux): maintain aspect ratio in s/w rendering pixel-buffer size clamping
- perf(android): use `hwdec=mediacodec` w/ `enableHardwareAcceleration`
- deps: migrate [`package:wakelock_plus`](https://pub.dev/packages/wakelock_plus)
