### ISSUE TITLE
Reaching object limit of OpenSL ES on Android

### ISSUE THREAD

**Issue by deckerst** [alexmercerind/media_kit#263]
When swiping through videos in my app, each creating/disposing a `Player` from `media_kit`, I can consistently make the app crash. I'd say after going through ~15 videos, but this is variable. In logcat, the most likely culprit is this:
```
2023-07-02 22:13:57.573 17929-20152 libOpenSLES             deckers.thibault.aves.profile        E  Too many objects
```

Digging a bit, here's some doc:
https://developer.android.com/ndk/guides/audio/opensl/opensl-for-android#limitations

> It supports a single engine per application and up to 32 objects per engine.

Are things properly disposed / recycled on the Android native side of  `media_kit`? Or maybe am I misusing your package?

**Comment by Quackdoc** [comment]
I believe this is actually related to another issue im about to post, but TLDR is it can take mpv up to 10s to dispose of media_kit currently due to the lock, this time increases for every new instance you start before another instance dies. so the first instance will take 10s second instance will take 20s third 30s etc.

I discovered this on windows but the locking mechanism is shared so I think it's safe to assume that this might be related. https://github.com/alexmercerind/media_kit/blob/75e26e9d28229c42f05fd87ba3843827b95194c5/media_kit/lib/src/player/libmpv/player/real.dart#L83

**Comment by alexmercerind** [comment]
Hi!
I'm currently at work & unable to make a detailed comment.

OpenSL ES limit doesn't cause a crash.

I'll be more helped by `adb logcat`, which will have the JNI crash stacktrace in it. It'll explain the cause.

Thanks!

**Comment by deckerst** [comment]
Logs:
[2023-07-03 19:30:51 logs aves profile media_kit crash.txt](https://github.com/alexmercerind/media_kit/files/11939824/2023-07-03.19.30.51.logs.aves.profile.media_kit.crash.txt)

**Comment by deckerst** [comment]
The app crashes, yes. But the attached log is filtered for the app process (`deckers.thibault.aves.profile`). Do you want unfiltered logs, with *all* processes?

**Comment by alexmercerind** [comment]
If you see something like "JNI ERROR DETECTED IN APPLICATION", then that's something I'm looking for.

**Comment by deckerst** [comment]
There's no log like "JNI ERROR DETECTED IN APPLICATION".

And here's an unfiltered log (debug level):
[2023-07-03 22:56:26 logs aves profile media_kit crash - all processes - level debug.txt](https://github.com/alexmercerind/media_kit/files/11940970/2023-07-03.22.56.26.logs.aves.profile.media_kit.crash.-.all.processes.-.level.debug.txt)

Just a precision about the app behaviour: it gets more and more sluggish before the crash, as if it gets more and more difficult on memory. This looks like a leak (or a dispose delay, as pointed in #266).

**Comment by alexmercerind** [comment]
The issue has been resolved.

Please refer to the ["Installation" section of the README](https://github.com/alexmercerind/media_kit#installation) to update.

Thanks!
