### ISSUE TITLE
Listening and exposing `video-out-params`

### ISSUE THREAD

**Issue by deckerst** [alexmercerind/media_kit#264]
Currently, it is possible to listen to the width/height streams from the player, but this size is the raw video size, not the actual rendered size. So it does not reflect the actual aspect ratio of the video (changed either because of rotation by metadata, or because of anamorphic pixels with a Sample Aspect Ratio different from 1).

On MPV side, it seems the info is available via the `video-out-params` events:
- https://github.com/mpv-player/mpv/issues/4367

I see [here](https://github.com/alexmercerind/media_kit/blob/main/media_kit/lib/src/player/libmpv/player/real.dart#L1865) the list of listened events, and just like you already listen and expose audio related events like `audio-params`, could you please expose `video-out-params`?

**Comment by deckerst** [comment]
Thanks for implementing it. I tried it and got all the info I needed, and more!

**Comment by alexmercerind** [comment]
The feature has been implemented.

Please refer to the ["Installation" section of the README](https://github.com/alexmercerind/media_kit#installation) to update.

Thanks!
