### ISSUE TITLE
[Question] min iOS version ?

### ISSUE THREAD

**Issue by dd9913762113** [alexmercerind/media_kit#267]
[!] CocoaPods could not find compatible versions for pod "media_kit_libs_ios_video":
                 In Podfile:
                   media_kit_libs_ios_video (from `.symlinks/plugins/media_kit_libs_ios_video/ios`)
           
               Specs satisfying the `media_kit_libs_ios_video (from `.symlinks/plugins/media_kit_libs_ios_video/ios`)` dependency were found, but they required a higher minimum deployment

**Comment by birros** [comment]
From https://github.com/media-kit/libmpv-darwin-build#notes

> The minimum versions of macOS and iOS have been chosen for these reasons:
> 
> - **macOS**: uchardet requires a minimum version of `10.9`
> - **iOS**: ffmpeg requires a minimum version of `13.0`
