### ISSUE TITLE
Need to shorten the time delayed to render and play video in linux.

### ISSUE THREAD

**Issue by lmmxxx** [alexmercerind/media_kit#270]
It takes like 10 seconds, for whatever size of video to start to play. Is there a way to shorten the delayed time? It seems like a constant 10 seconds total have been set to delayed before playing the video.

**Comment by alexmercerind** [comment]
It does not. Provide URL or blame your internet.

**Comment by lmmxxx** [comment]
I mean I also tested on local video files, whatever the size, always taken exact 10 seconds to play.

**Comment by Quackdoc** [comment]
what are your system specs? I test regularly and don't have those issues. off the top of my head it could be a couple issues 

- wierd formats can take a while to parse
- audio issues (pipewire, pulse, jack, alsa are all supported, if one of those on the host is buggy it can take a while to fallback)
- high bitrate data can take a while to load in if loading from HDD
- very hard to decode formats like highly compressed image sequences 

None of these issues are directly related to media_kit however

**Comment by lmmxxx** [comment]
hardware specs: 5950X+X570E-STRIX+64GB 3200+SN550 1T+PM1735 3.2T
 I've tested local files on both SSDs, and a seagate exos 16T HDD, with video file format mp4 and mkv,  whatever combination, takes exact 10 seconds to play, so it doesn't seem to be related to hardware or file format.
[✓] Flutter (Channel stable, 3.10.5, on Fedora Linux 38 (Workstation Edition) 6.3.8-200.fc38.x86_64, locale en_US.UTF-8)
    • Flutter version 3.10.5 on channel stable at /home/xxx/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

**Comment by alexmercerind** [comment]
1. Please try the example application (link available in README).
2. Please test how does mpv itself perform.

**Comment by lmmxxx** [comment]
I've tested the example first and made sure mpv plays video instantly. 
I also tested modifying the enable hardware acceleration to false, which afterwards also takes exact 10 seconds to play.

**Comment by lmmxxx** [comment]
I think I found what causes the problem,  the GPU, and I doubt it might relate to how hardware acceleration is implemented.
I changed the GPU from INTEL ARC 380 to RTX 4090 and then a NVIDIA T600, it plays immediately, no constant 10 seconds delay. And with whatever GPU it doesn't make a difference with/without enableHardwareAcceleration set to false,  10 seconds delay for INTEL GPU, 0 seconds for NVIDIA GPU.

**Comment by Quackdoc** [comment]
sounds like hwdec might be failing to initialize?

**Comment by alexmercerind** [comment]
Apologies for the delays. I happen to be kind-of occupied these days.

Please know that you'll be able to help out yourself best here. The issue is specific to your machine or OS; there's very little I can guide here. The project will be helped by your discovery & we're ready to account for fixes/reports that you provide.

Thanks!

**Comment by alexmercerind** [comment]
You can subscribe to libmpv's internal logs by passing to `PlayerConfiguration` & then printing `player.stream.log`.

This will help you get an idea about what mpv is doing under the hood to cause this delay.

**Comment by alexmercerind** [comment]
We can't really reproduce.
