### ISSUE TITLE
[Question] How to add "--no-video" option to the "mpv"?

### ISSUE THREAD

**Issue by AndroidDesigner** [alexmercerind/media_kit#274]
Hello
I'm going to use the ``media_kit`` package in a linux-based project and I need play mp3 files with ``--no-video`` option.
How can I add options to the ``mpv``?

**Comment by solsticedhiver** [comment]
I hope someone correct me if I am wrong, but if I remember correctly the top of the READM.md, it says to use `media_kit_ libs_*_audio` lib if you need only audio.

So there would be no need for such option.

If you need video, and include the `media_kit_libs_*_video` lib, and you need to read an audio file, you can disable a video track with:

    await player.setVideoTrack(VideoTrack.no());

JRTFM

**Comment by AndroidDesigner** [comment]
Thank you. it worked!
