### ISSUE TITLE
[Question] [windows] [build] Dependent library download

### ISSUE THREAD

**Issue by chifandeyu** [alexmercerind/media_kit#285]
Had a suggestion. Dependency library will download to "project\build \windows\", When run "flutter clean" it will be deleted, then  rebuild need to re-download. Can download  it to "pub\cache\hosted\pub.dev\media _kit_libs_windows__video-1.0.2\ windows"? Hope the plugin dependency library will not be deleted when my project build directory be deleted.

![image](https://github.com/alexmercerind/media_kit/assets/15946864/f1778f09-154b-40d6-b332-dd06e04e0573)

**Comment by alexmercerind** [comment]
Native Android dependencies are also cleared in a similar way. Secondly, download may fail sometimes, in those cases flutter clean works as expected.
