### ISSUE TITLE
Bad performance, jerks on windows

### ISSUE THREAD

**Issue by braindamagedman** [alexmercerind/media_kit#290]
Hello,

I am trying to use this plugin to show RTP stream. 

I have this setup:
- RTP stream of 1920x1080 H265 video, 30FPS
- flutter client with media_kit on Windows

I saw permanent small jerks on video. And when i investigated this problem i found, that problem is - raster thread spend a lot of time doing job (Raster Jank Detected). And i found that even if there is no video input (just progress indicator in video widget), i have same problem.

When i run MPV player itself (`.\mpv.com rtp://@0.0.0.0:5202 -no-cache --untimed  --no-demuxer-thread --vd-lavc-threads=1`) - there is no jerks.

This are screens from flutter performance when no video input, profile build:
![Screenshot 2023-07-19 174236](https://github.com/alexmercerind/media_kit/assets/1287597/77a3996f-e472-463f-b36d-39e94fc430c3)

![Screenshot 2023-07-19 191507](https://github.com/alexmercerind/media_kit/assets/1287597/8177f04a-9fbe-4872-9751-1534ed65510b)

## Steps to reproduce:
- Create new flutter app
- Put this code inside main.dart:
```dart
class _MyHomePageState extends State<MyHomePage> {
  final playable = Media('rtp://@0.0.0.0:5200');
  final PlayerConfiguration config = const PlayerConfiguration(
    protocolWhitelist: [
      'file',
      'tcp',
      'tls',
      'http',
      'https',
      'crypto',
      'data',
      'rtp',
    ],
  );
  late final Player player = Player(configuration: config);
  late final VideoController controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    player.open(playable);
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SizedBox(
        width: 1920,
        height: 1080,
        // Use [Video] widget to display video output.
        child: Video(controller: controller),
      ),
    );
  }
}
```
- Run application in profile or release mode.

## My env:
Win 11 Pro
AMD Ryzen 5 PRO 5650U with Radeon Graphics        2.30 GHz

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22621.1778])
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.5)
[√] Android Studio (version 2022.1)
[√] Android Studio (version 2022.2)
[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
[√] VS Code (version 1.80.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

```

I also receive similar results on other machine

## Output from application:
```
Launching lib\main.dart on Windows in profile mode...
Building Windows application...
package:media_kit_libs_windows_video registered.
Problem getting monitor brightness
Debug service listening on ws://127.0.0.1:51864/ZUgUmJhPvdM=/ws
AMD Radeon(TM) Graphics
media_kit: ANGLESurfaceManager: Direct3D Feature Level: 11_0
1 1
media_kit: VideoOutput: Create Texture: 2317518596688
media_kit: VideoOutput: Using H/W rendering.
flutter: VideoOutput.Resize
flutter: {handle: 2317405222352, id: 2317518596688, rect: {height: 0, left: 0, top: 0, width: 0}}
flutter: NativeVideoController: Texture ID: 2317518596688
```

What i can do to solve this problem?

**Comment by alexmercerind** [comment]
First of all, thanks for providing a descriptive report! 🙏 (× 100).

<hr>

I know it's surprising but [`CircularProgressIndicator` in Flutter is very heavy](https://github.com/flutter/flutter/issues/13203). The said "jerk" or raster jank may be entirely due to it. Our sample plays multiple HD videos at once without much significant load. This was recently brought to my attention internally; I'm thinking about replacing it with some lighter widget.

Our default `MaterialVideoControls` & `MaterialDesktopVideoControls` use it to indicate buffering. You can try to disable video controls by passing [`controls: NoVideoControls`](https://github.com/alexmercerind/media_kit#novideocontrols) to `Video` widget.

**Comment by alexmercerind** [comment]
Feel free to share your feedback.

I personally cannot see any jank on Windows. Even the ripple on the `InkWell`s (when `open`-ing a media) animates very smoothly. The [video frame is rendered on another thread](https://github.com/alexmercerind/media_kit/blob/8215e727cfeb6d1aee4c576956a671beb4e3b297/media_kit_video/windows/video_output.cc#L157-L163); while [Flutter's render thread just reads the already rendered frame](https://github.com/alexmercerind/media_kit/blob/8215e727cfeb6d1aee4c576956a671beb4e3b297/media_kit_video/windows/video_output.cc#L321-L327). This significantly improved the jank in past & possibly that's the best one can get.

As for CPU usage, it can be improved further once direct DirectX 11 API is worked on. However, even in current state package:media_kit outperforms Google Chrome's video playback.

**Comment by alexmercerind** [comment]
Wanna say something?

**Comment by alexmercerind** [comment]
Like you said "jerk" even occurs for you while video isn't playing there's nothing that can be done unless you provide some information.

**Comment by alexmercerind** [comment]
https://github.com/alexmercerind/media_kit/assets/28951144/a445f9a3-f17e-47a8-b75b-38e5d3d18f87

This is the performance on my 350$ laptop having entry-level Ryzen 3 2200U with integrated Radeon Vega 3 graphics. It should be better on a more capable GPU/CPU.

The performance can be improved further in future but I believe it has nothing to do with what you're experiencing.
