### ISSUE TITLE
Add support for textScaleFactor

### ISSUE THREAD

**Issue by kirill-21** [alexmercerind/media_kit#299]
Can you please add support for textScaleFactor in MaterialDesktopPositionIndicator widget? For apps with custom scaling

**Comment by alexmercerind** [comment]
It's not really relevant for textScaleFactor. The Flutter UI itself gets scaled based on scale factor your display has.

**Comment by alexmercerind** [comment]
Sitll... Feel free to raise a PR & we can provide feedback.

**Comment by kirill-21** [comment]
> Sitll... Feel free to raise a PR & we can provide feedback.

I'm talking about custom scaling, i know that windows by default uses it's own scale factor, but what if your app has an additional one?

**Comment by alexmercerind** [comment]
Then it's YOUR app.
