### ISSUE TITLE
bitsdojo_window   conflict

### ISSUE THREAD

**Issue by pufaqi** [alexmercerind/media_kit#301]
media_kit: ^1.1.0
  media_kit_video: ^1.1.0
  media_kit_native_event_loop: ^1.0.6
  media_kit_libs_windows_video: ^1.0.4
  bitsdojo_window: ^0.1.5

error message：
Because bitsdojo_window >=0.1.5 depends on bitsdojo_window_windows ^0.1.5 which depends on win32 ^3.0.0, bitsdojo_window >=0.1.5 requires win32 ^3.0.0.
And because wakelock_plus 1.1.1 depends on win32 >=4.0.0 <6.0.0 and no versions of wakelock_plus match >1.1.1 <2.0.0, bitsdojo_window >=0.1.5 is incompatible with wakelock_plus ^1.1.1.
And because media_kit_video 1.1.0 depends on wakelock_plus ^1.1.1 and no versions of media_kit_video match >1.1.0 <2.0.0, bitsdojo_window >=0.1.5 is incompatible with media_kit_video ^1.1.0.
So, because media_ts depends on both media_kit_video ^1.1.0 and bitsdojo_window ^0.1.5, version solving failed.

**Comment by alexmercerind** [comment]
How is it my fault & not bitsdojo_window???
