### ISSUE TITLE
soure code build fail

### ISSUE THREAD

**Issue by sofm13** [alexmercerind/media_kit#303]
when i test soure code /media_kit_test ,I get this fail log.

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!

Failed to send crash report due to a network error: 信号灯超时时间已到

Oops; flutter has exited unexpectedly: "FileSystemException: Failed to decode data using encoding 'utf-8', path =
'F:\zsq\flutter\media_kit\libs\android\media_kit_libs_android_video\android\src\main\java\com\alexmercerind\media_kit_libs_android_video\MediaKitLibsAndroidVideoPlugin.java'".

**Comment by alexmercerind** [comment]
To our CI, where builds are succeeding. Check your connection etc.

**Comment by alexmercerind** [comment]
https://github.com/alexmercerind/media_kit/actions/runs/5642682110/job/15283009598
