### ISSUE TITLE
Guide how to organize dlls on Windows after building the app

### ISSUE THREAD

**Issue by kirill-21** [alexmercerind/media_kit#304]
Hello, lately I started using this package and didn't like that there are dozens of dlls in the same folder where main app's exe is located. So I decided to fix it and did a little research to do it. If there would be any other people who are interested in this, feel free to use this method.

@alexmercerind, maybe you can add this to a ReadME or somewhere else so that this could be easily found?

If you're using this package you might have noticed that there are a lot packed dlls that are placed near the main .exe file. For those who do not like it and want to make the files structure a little bit cleaner i've made this guide.

**1. Go to your project, open "Windows" folder and find CMakeLists.txt file.**
**2. Open this file and find these two lines:**
```CMake
set(INSTALL_BUNDLE_DATA_DIR "${CMAKE_INSTALL_PREFIX}/data")
set(INSTALL_BUNDLE_LIB_DIR "${CMAKE_INSTALL_PREFIX}")
```
and change them to this:
```CMake
set(INSTALL_BUNDLE_LIB_SUBDIR "media_kit") # Here you can choose any name for the folder where all dlls from this package will be located
set(INSTALL_BUNDLE_DATA_DIR "${CMAKE_INSTALL_PREFIX}/data")
set(INSTALL_BUNDLE_LIB_DIR "${CMAKE_INSTALL_PREFIX}/${INSTALL_BUNDLE_LIB_SUBDIR}")

# Delay main plugin dlls loading to avoid "The code execution cannot proceed because ...dll was not
# found" error
target_link_options(${BINARY_NAME} PRIVATE "/DELAYLOAD:screen_brightness_windows_plugin.dll")
target_link_options(${BINARY_NAME} PRIVATE "/DELAYLOAD:media_kit_libs_windows_video_plugin.dll")
target_link_options(${BINARY_NAME} PRIVATE "/DELAYLOAD:media_kit_video_plugin.dll")
```
**3. Find this two line of code in the same file:**
```CMake
install(FILES "${FLUTTER_LIBRARY}" DESTINATION "${INSTALL_BUNDLE_LIB_DIR}"
  COMPONENT Runtime)
```
and replace them with this:
```
install(FILES "${FLUTTER_LIBRARY}" DESTINATION "${CMAKE_INSTALL_PREFIX}"
  COMPONENT Runtime)
```
This code will make sure that flutter_windows.dll is located at the same folder where your main executable is being compiled
**4. Scroll down to the last line in this file and add there the following code:**
```CMake
# Copy main flutter dlls from [https://docs.flutter.dev/platform-integration/windows/building]
# to the same folder where app's executable is located. Remove dlls from their original source path
# after copying.
set(SOURCE_FILES
  "${CMAKE_CURRENT_BINARY_DIR}/runner/Release/${INSTALL_BUNDLE_LIB_SUBDIR}/msvcp140.dll"
  "${CMAKE_CURRENT_BINARY_DIR}/runner/Release/${INSTALL_BUNDLE_LIB_SUBDIR}/api-ms-win-crt-runtime-l1-1-0.dll"
  "${CMAKE_CURRENT_BINARY_DIR}/runner/Release/${INSTALL_BUNDLE_LIB_SUBDIR}/vcruntime140.dll"
  "${CMAKE_CURRENT_BINARY_DIR}/runner/Release/${INSTALL_BUNDLE_LIB_SUBDIR}/vcruntime140_1.dll"
)
install(CODE "
  execute_process(COMMAND ${CMAKE_COMMAND} -E copy ${SOURCE_FILES} ${CMAKE_CURRENT_BINARY_DIR}/runner/Release)
  file(REMOVE ${SOURCE_FILES})
")
```
**5. Navigate to Windows/runner/main.cpp and add this method below all includes**
```c++
// Tries to add provided path to the set of directories that are searched for a DLL
void _addFolderToLookable(std::wstring path) {
  // Construct the path to the binaries folder
  std::wstring dllDirectory = path + L"\\" + L"media_kit";

  // Try multiple WinAPI methods in case one won't work (due to old windows versions, etc.)
  AddDllDirectory(dllDirectory.c_str());
  SetDllDirectoryW(dllDirectory.c_str());
}
```
then add the following code to the beginning of wWinMain method:
```c++
  // Add path to [INSTALL_BUNDLE_LIB_SUBDIR] variable from CMake so that all /DELAYLOAD dlls
  // can be loaded
  WCHAR exePath[MAX_PATH];
  DWORD pathLength = GetModuleFileName(0, exePath, MAX_PATH);
  if (pathLength != 0 && !std::wstring(exePath).empty()) {
    // Extract the directory path from the executable path
    std::wstring exeDirectory = exePath;
    size_t lastSeparator = exeDirectory.find_last_of(L"\\/");
    exeDirectory = exeDirectory.substr(0, lastSeparator + 1);

    _addFolderToLookable(exeDirectory);
  } else {
    // Try one more way of retrieving current app's folder
    pathLength = GetCurrentDirectory(MAX_PATH, exePath);
    if (pathLength != 0) {
      std::wstring exeDirectory = exePath;
      if(!exeDirectory.empty()) _addFolderToLookable(exeDirectory);
    }
  }
```
Make sure #include <windows.h> and #include <psapi.h> are included at the top of the file.

Result: All default flutter dlls are located near the main executable and all plugin dlls can be found in media_kit directory. This methods supports all windows versions from 7 to 11.
![image](https://github.com/alexmercerind/media_kit/assets/63228361/b750e196-386e-4f32-a667-23aebf308498)

**Comment by alexmercerind** [comment]
You generally don't provide a folder of your application to your users when distributing software for Windows. There are dedicated packaging formats e.g. MSI, EXE, MSIX that you can use (they generate dedicated entries inside Start Menu & desktop etc.). Personally, I can recommend [INNO Setup](https://github.com/harmonoid/harmonoid/blob/master/Harmonoid_InnoSetup.iss
). 

I'm not really convinced by the idea of playing around with this. We follow the default package/plugin formats provided by Flutter & it'll be good to keep doing it, in order to avoid any breaking behavior in the future.

As a matter of fact, most DLLs shipped with package:media_kit are from UCRT & MSVCRT, to not require a separate installation of Visual C++ Runtime on consumer's machines.

**Comment by alexmercerind** [comment]
Thanks for sharing your research.

**Comment by kirill-21** [comment]
> You generally don't provide a folder of your application to your users when distributing software for Windows. There are dedicated packaging formats e.g. MSI, EXE, MSIX that you can use (they generate dedicated entries inside Start Menu & desktop etc.). Personally, I can recommend [INNO Setup, which I used in my project (also uses package:media_kit)](https://github.com/harmonoid/harmonoid/blob/master/Harmonoid_InnoSetup.iss).
> 
> I'm not really convinced by the idea of playing around with this. We follow the default package/plugin formats provided by Flutter & it'll be good to keep doing it, in order to avoid any breaking behavior in the future.
> 
> As a matter of fact, most DLLs shipped with package:media_kit are from UCRT & MSVCRT, to not require a separate installation of Visual C++ Runtime on consumer's machines.

I know, just a guide for those people who share their apps as an ordinary zip archive and do not want to use installers.
