### ISSUE TITLE
[Question][GNU/Linux] How to include libmpv in the linux build / AppImage?

### ISSUE THREAD

**Issue by tomekit** [alexmercerind/media_kit#308]
When I build a Linux release and distribute it externally it can't be opened due to:
```
error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
```
that's somewhat expected if `libmpv` isn't installed.

Documentation provides Flatpak: https://github.com/celluloid-player/celluloid/blob/master/flatpak/io.github.celluloid_player.Celluloid.json
and generic packaging including AppImage: https://github.com/ozmartian/vidcutter/tree/master/_packaging/appimage

The thing is that the AppImage example is actually using: https://github.com/AppImageCommunity/pkg2appimage which is converting existing .deb package to AppImage format, so it's not straightforward to me how to use it for Flutter.

Is there any simple workaround to include the missing `libmpv.so.1` in the `build/linux/x64/release/bundle` and then creating the AppImage?

Sorry if this isn't really media_kit question, but more about Flutter and the libraries, but I've assumed someone might actually resolved that and be able to help.

**Comment by alexmercerind** [comment]
Hi!

I can't really provide any consultation related to GNU/Linux software distribution practices. Please use a search engine.

<hr>

As far as it is concerned, depending upon distribution packages (`apt`; `rpm`) & sharing libraries (`*.so`) is the "philosophy" in GNU/Linux operating systems. For instance, your software package will depend upon libmpv that the user installed, which itself will depend upon FFmpeg user installed, which itself will depend upon libraries that the user installed. I also don't find it optimal but that's how GNU/Linux works. Recently, people have started creating standalone packages e.g. FlatHub, AppImage, Snap etc. where you provide your own version of libraries that are bundled with your package.

[Musicpod](https://github.com/ubuntu-flutter-community/musicpod) can be another project example which is [distributed through Ubuntu Snap Store](https://snapcraft.io/install/musicpod/ubuntu) & uses package:media_kit.

I, unfortunately, don't have the time to create a standalone static libmpv for GNU/Linux. Other platforms have a higher focus (for obvious reasons) at the moment. [package:media_kit provides it's own minimal libmpv builds for Windows, GNU/Linux, macOS & iOS](https://github.com/media-kit), ideally I'd like to offer same on GNU/Linux.

Thanks!

**Comment by alexmercerind** [comment]
With that being said, the last update further reduced bundle sizes by a large factor, you might be interested in updating.

**Comment by alexmercerind** [comment]
In my project, [Harmonoid](https://harmonoid.com/downloads) (uses package:media_kit), I only distribute distribution-specific packages at the moment.
