### ISSUE TITLE
[Bug Report] audio files with embedded artwork not playing

### ISSUE THREAD

**Issue by coolight7** [alexmercerind/media_kit#309]
* Hi,
* I had use `media_kit: ^1.1.0`. 
* It will show an black screen when play a song has png album cover and get an error `Failed to initialize a decoder for codec 'png'`. 
* I think i should use the full lib. And i had find it:
```
https://github.com/media-kit/libmpv-android-video-build/releases/
```
* But i don't know how to add it in my pubspec.yaml, please help me.
### The other question is it will get an error when call MediaKit.ensurelnitialized() if add package `ffmpeg_kit_flutter_full`:
```
Exception: Cannot find libmpv.so.Please ensure it'spresence in the APK
#0 NativeLibrary.ensurelnitialized (package:media_kit/src/player/native/core/native_library.dart:73)
#1 nativeEnsurelnitialized(package:media_kit/src/player/native/player/real.dart:49)
#2 MediaKit.ensurelnitialized(package:media_kit/srcmedia_kit.dart:31)
#3 AudioStore.initAudioUseLib (package:mymusic/store/AudioStore.dart:616)<asynchronous suspension>
#4 MyApp.initStore (package:mymusic/main.dart:154)<asvnchronous suspension>
#5 runMain(package:mymusic/main.dart:84)
<asynchronous suspension>
```
* it work well if i use media_kit 1.0.2 and it's lib. 
* now my pubspec.yaml:
```
  media_kit: ^1.1.0
  media_kit_video: ^1.1.0
  media_kit_native_event_loop: ^1.0.6
  media_kit_libs_android_video: ^1.2.0
  media_kit_libs_windows_video: ^1.0.4
  # ffmpeg_kit_flutter_full: 5.1.0-LTS  # i had remove it after use media_kit 1.1.0
```
Thanks!

**Comment by alexmercerind** [comment]
You won't need `full` variant to play audio files, it's a bug.

**Comment by coolight7** [comment]
> You won't need `full` variant to play audio files, it's a bug.

haha, ok, i will wait for you fix it.

**Comment by alexmercerind** [comment]
What is your device's architecture?

**Comment by coolight7** [comment]
> What is your device's architecture?

arm64, Android 11
cpu: snapdragons 855+

**Comment by alexmercerind** [comment]
Other users are able to use media_kit with ffmpeg_kit_flutter. 

https://github.com/alexmercerind/media_kit/issues/283

Can you print exception & stack-trace by editing this line & see what error comes:

https://github.com/alexmercerind/media_kit/blob/f2918c0a2223aa4fe8434127b3969c016ba40eac/media_kit/lib/src/player/native/core/native_library.dart#L69

**Comment by alexmercerind** [comment]
I'll try to fix few recently reported issues in few hours & publish an update.

**Comment by coolight7** [comment]
it print:
```
I/flutter (31683): Invalid argument(s): Failed to load dynamic library 'libmpv.so': dlopen failed: cannot locate symbol "av_log_default_callback" referenced by "/data/app/~~lBWKPObsQGofrJwnvR2jiw==/com.mimicry.mymusic-kD_acH0KeHXonOezPSraTw==/lib/arm64/libmpv.so"...
```

**Comment by alexmercerind** [comment]
Does non-LTS version work? I will go ahead & link static, too many issues.

**Comment by coolight7** [comment]
It is still not available. But it doesn't matter to me, i don't need it after media_kit has af=equalizer for Android.

**Comment by alexmercerind** [comment]
It's already available.

**Comment by alexmercerind** [comment]
@coolight7 did you manually try to enable embedded image in audio files?

We have it disabled:

https://github.com/alexmercerind/media_kit/blob/7c95f7e0a140fc33ce4880e78f396d2ac9333b81/media_kit/lib/src/player/native/player/real.dart#L2075

You must not face the error you reported above.

**Comment by alexmercerind** [comment]
I'm just unable to comprehend, how & why you are loading images?

**Comment by coolight7** [comment]
> I'm just unable to comprehend, how & why you are loading images in a video/audio library?
> 
> If you are utilizing setProperty API; then you are using libmpv (NOT media_kit) & you are accountable/responsible for everything.

* yes, i had set audio-display "embedded-first" to enable.
* Because many plugins read the artwork are weak ability（most can only be used for mp3/flac）, and can not the network audio file, we must download to a local file before we can read it.
* mpv can meet these needs if enable 'audio-display'. so i want to use it.
* Currently, none of the media player plugins I have encountered have the stream to listen the artwork/title/artist/lyric ..... But it is Important and disturbing us. mpv itself has done a great job in this area, maybe it can become media_kit highlight.

**Comment by alexmercerind** [comment]
Use mpv then not media_kit.

Flutter has built-in decoders for image & Android has dedicated APIs to extract embedded artwork from audio files. Use them.

We have a number of additional configurations (in some cases, even custom patches over mpv) to make everything work, you can't just replace one option randomly & then blame us. I can only provide support for the code I wrote & features I provide in the package, not outside that. If you modify some internal flag, it's your responsibility. It's like forking the package & blaming for the code you wrote.

There's a reason I added/removed those flags.

**Comment by alexmercerind** [comment]
As for using custom libmpv builds, bundle them yourself. Read the code probably.
