### ISSUE TITLE
[Question] Demuxer cache size

### ISSUE THREAD

**Issue by AALAMILLO** [alexmercerind/media_kit#311]
Hi! that is not at issue at all. i had been try to seek my video 10 seconds (Forward or back) but it takes a lot of time. This seek has to be quickly cause the buffer right? 

The code:
await player.seek(player.state.position - const Duration(seconds: 10));

await player.seek(player.state.position + const Duration(seconds: 10));

**Comment by alexmercerind** [comment]
Hi!

You can try to increase buffer size, by default it is small to reduce RAM usage:

https://github.com/alexmercerind/media_kit/blob/7c95f7e0a140fc33ce4880e78f396d2ac9333b81/media_kit/lib/src/player/platform_player.dart#L429-L432

Also:

- Which platform?
- Network URL or File?

**Comment by AALAMILLO** [comment]
Thanks for answering.... i´m sorry where can i do this? in my player configuration i can only modify this parameters:

![image](https://github.com/alexmercerind/media_kit/assets/71103258/368620e3-faa5-4d01-bd60-3a1eedd64a1d)

**Comment by alexmercerind** [comment]
```dart
final Player player = Player(
  configuration: PlayerConfiguration(
    // Supply your options:
    bufferSize: 128 * 1024 * 1024,
  ),
);
```

**Comment by AALAMILLO** [comment]
I'm going to try it. Which Video controller configuration do you recommend for an Android TV? I just set enable hardware acceleration as true.

My video is on network by the way

**Comment by alexmercerind** [comment]
It should work fine by default.

Just make sure that you're on the latest version; there have been a number of major improvements for Android.

**Comment by alexmercerind** [comment]
Hi @AALAMILLO,

Any improvements?

**Comment by AALAMILLO** [comment]
Hi! I just try it. It works great. How much buffer you recommends? The max to have a better performance? After this thanks a lot you can close this.

**Comment by AALAMILLO** [comment]
Hi again. It takes a long too when i change subtitles: await widget.player.setSubtitleTrack(track); and when i change the audio track: await widget.player.setAudioTrack(track);..... Any tip?

**Comment by alexmercerind** [comment]
If it's a network stream, it will obviously take time to fetch the subtitles. I can't say much.

You may join our Discord (link in the README) for additional feedback; let's keep GitHub Issues for bug-reports.

Thanks!
