### ISSUE TITLE
[Feature Request] Buffering progress

### ISSUE THREAD

**Issue by bdlukaa** [alexmercerind/media_kit#35]
An option to know the current buffering progress. This is useful to use in a slider alongside with the current player position

**Comment by alexmercerind** [comment]
I have to see if that's possible. Currently working on other issues.

**Comment by Quackdoc** [comment]
I don't have the time to work on this yet but it's likely possible to make use of the [demuxer-cache-state](https://mpv.io/manual/master/#command-interface-demuxer-cache-state) property for this. it's also possible to set custom cache size using mpv properties. it returns the value as `cache-end` or we can use the dedicated property `demuxer-cache-time`. both are the same value. demuxer-cache-state will simple also return other values as listed in the link.
