### ISSUE TITLE
[Question] More Log-Output, Location of Temp-Dir (if used)

### ISSUE THREAD

**Issue by filly82** [alexmercerind/media_kit#37]
when opening files from my NAS (mounted as an Windows Network Share) then it takes minutes for these files to start playing, approximately the same amount of time it would need to copy these files to local storage. 
is that or something similar maybe happening with network files? if so (and in general) are there any temporary/logging directories for this package and/or the libraries it's using?

some other files cannot be opened at all (local or network), the app always crashes with these files, I just see a "Lost connection to device". 
are there any logfiles written somewhere or is there a possibility to see more logging output in order to investigate the problem with these files? they work with VLC or the official mpv-Player but not with the package

**Comment by alexmercerind** [comment]
Please deal with these issues on your own. 100% of the implementation is in Dart & if you want to edit anything, you very well can, there is also an API to set custom libmpv flags, properties or options.

**I do not have the resources, time or interest in providing consultancy.**

All documentation about [mpv is publicly available on the internet](https://mpv.io/manual/stable/) & will clearly guide about enabling logging, caching etc. You might need tweaking or setting of certain options or properties based on your project's specific needs. I'm offering best suited abstracted API for a generalized use case in [package:media_kit](https://github.com/alexmercerind/media_kit).

**Comment by alexmercerind** [comment]
I will be fine with accepting any pull-requests if you expose any other libmpv APIs yourself in high-level `Player` class abstraction (like I've done). But, please bear with the review process if you do so.

**Comment by alexmercerind** [comment]
Wait... Something just came to my mind.

Can you specify `uri_parser` to `2.0.0` in `dependency_overrides`  of your pubspec.yaml. It should fix the issue.

See: https://github.com/harmonoid/harmonoid/blob/9ccc4ee116b5e4f19c462756403d5db9eb2def6f/pubspec.yaml#L121
