### ISSUE TITLE
[Question] Listen for network errors

### ISSUE THREAD

**Issue by JulienDev** [alexmercerind/media_kit#39]
Hello!
First of all, thank you for this awesome new project!
I'd like to know if it's possible to listen for network errors. I'm listening to the `player.stream.error` stream but when I enable the airplane mode, no error is raised. Is there any other solution?
Thanks!

**Comment by alexmercerind** [comment]
I'm pretty sure if you connect back to internet, it'll start playing back again. That's how mpv works. It's not an "error".

**Comment by JulienDev** [comment]
I've tried and when the internet is back the stream doesn't play again, unfortunately, that's why I was expecting a way to know that an "error" happened

**Comment by alexmercerind** [comment]
There's also [`--network-timeout`](https://mpv.io/manual/stable/#options-network-timeout). Like other things on the page, I haven't exposed everything in my abstracted API. However, you can set it [like this](https://github.com/alexmercerind/media_kit/issues/14#issuecomment-1373205132) (do it before opening something to play).

Thanks!

**Comment by JulienDev** [comment]
Thank you, I'll try ASAP

**Comment by Quackdoc** [comment]
@JulienDev follow up?

**Comment by JulienDev** [comment]
Unfortunately I'm still not able to make it work. I played with parameters : `network-timeout` and `cache` but the error callback is never called. Also the stream is not restarted when internet is back. That's a bit frustrating because I have to restart the stream manually each time a network error is happening.

**Comment by birros** [comment]
As @alexmercerind suggested in pull request #62, with the addition of mpv logs support in main, @JulienDev can you check if you are getting now the logs you want?

You must create a player with these options:
```dart
final Player player = Player(
  configuration: const PlayerConfiguration(
    events: true,
    logLevel: MPVLogLevel.warn,
  ),
);
```
The `warn` parameter is used to catch warnings and errors.

You have now access to logs:
```dart
void pipeLogsToConsole(Player player) {
  player.streams.log.listen((event) {
    if (kDebugMode) {
      print("mpv: ${event.prefix}: ${event.level}: ${event.text}");
    }
  });
}
```

If that's not enough I don't think it's up to **media_kit** to handle network errors, since it's the **mpv** / **ffmpeg** duo that takes care of network requests, am I wrong?

**Comment by JulienDev** [comment]
Unfortunately, it's not helping. These are the logs I get in the console when I'm watching a live stream and switch off the network : 

> flutter: mpv: cplayer: warn: Audio device underrun detected.
> flutter: isBuffering:true

A few seconds later
> flutter: isBuffering:false
> flutter: mpv: ffmpeg/video: warn: h264: vt decoder cb: output image buffer is null: -12909
> flutter: mpv: ffmpeg/video: error: h264: hardware accelerator failed to decode picture
> flutter: mpv: vd: warn: Error while decoding frame (hardware decoding)!
> flutter: mpv: ffmpeg/video: error: h264: No frame decoded?
> flutter: mpv: vd: warn: Error while decoding frame (hardware decoding)!


IMO media_kit should at least inform the developer when the network requests are failing. Then the developer will decide what to do (display error, retry, close the player...).

**Comment by birros** [comment]
Tested with `media_kit_test`:

Like you, just after disabling the network, I get this:
```
flutter: mpv: cplayer: warn: Audio device underrun detected.
```

But unlike you, after a few seconds ffmpeg informs me of a tcp error:
```
flutter: mpv: ffmpeg: warn: http: Will reconnect at 10251354 in 0 second(s), error=Operation timed out.
flutter: mpv: ffmpeg: error: tcp: Connection to tcp://commondatastorage.googleapis.com:80 failed: Network is unreachable
flutter: mpv: ffmpeg: warn: http: Will reconnect at 10251354 in 1 second(s), error=Operation timed out.
flutter: mpv: ffmpeg: error: tcp: Connection to tcp://commondatastorage.googleapis.com:80 failed: Network is unreachable
```

**Comment by birros** [comment]
Since it is ffmpeg that takes care of network requests, if it doesn't report tcp errors every time, maybe there is an option missing in the ffmpeg build, or simply the normal behavior or a bug in ffmpeg.

**Comment by JulienDev** [comment]
> Tested with `media_kit_test`:
> 
> Like you, just after disabling the network, I get this:
> ```
> flutter: mpv: cplayer: warn: Audio device underrun detected.
> ```
> 
> But unlike you, after a few seconds ffmpeg informs me of a tcp error:
> ```
> flutter: mpv: ffmpeg: warn: http: Will reconnect at 10251354 in 0 second(s), error=Operation timed out.
> flutter: mpv: ffmpeg: error: tcp: Connection to tcp://commondatastorage.googleapis.com:80 failed: Network is unreachable
> flutter: mpv: ffmpeg: warn: http: Will reconnect at 10251354 in 1 second(s), error=Operation timed out.
> flutter: mpv: ffmpeg: error: tcp: Connection to tcp://commondatastorage.googleapis.com:80 failed: Network is unreachable
> ```
> 

Did you try with a live streaming video or just a static video?

**Comment by birros** [comment]
A static video: https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

Also, the previous logs I provided were for the `http` address, here are the `https` ones:
```
flutter: mpv: ffmpeg: error: tls: read failed: error:14FFF3E7:SSL routines:(UNKNOWN)SSL_internal:unknown failure occurred
flutter: mpv: ffmpeg: warn: https: Will reconnect at 21728009 in 0 second(s), error=Input/output error.
flutter: mpv: ffmpeg: error: tcp: Connection to tcp://commondatastorage.googleapis.com:443 failed: Network is unreachable
```

**Comment by birros** [comment]
What protocol do you use? Maybe it comes from this.

**Comment by birros** [comment]
Knowing that:
- the logs are now programmatically accessible: #62
- the buffering information is easily accessible: #122 & #125
- no one else has added a comment for a month

I decide to close this issue.
Feel free to reopen it or add comments if needed 🙂
