### ISSUE TITLE
[Enhancement] macOS support

### ISSUE THREAD

**Issue by ProgramerMartin** [alexmercerind/media_kit#43]
I can't find a suitable library on macOS.

How long can I expect to support macOS?

**Comment by alexmercerind** [comment]
Am I supposted to answer this question?

Sorry, the code here in this repository (no matter how good it may be), is provided without any obligation or warranty.

https://github.com/alexmercerind/media_kit/blob/4b02f9caba41df042d59f44b2f65ce8fde2cf1c9/LICENSE#L15-L21

There are a number of tasks, even Windows or GNU/Linux implementation has not been released on pub.dev yet. I'd like to fix #40 first. At the moment, I don't even own a macOS running device, so I have to think about it.

**Comment by alexmercerind** [comment]
> I'm working on a macOS implementation, it works, but as I'm starting from scratch, I need more time to integrate it into mediakit. I plan to create a pull request soon.

I hope you are using libmpv video embedding API ([`render.h`](https://github.com/mpv-player/mpv/blob/master/libmpv/render.h)), it will allow us to keep using same 90-ish % common Dart implementation inside [`package:media_kit`](https://github.com/alexmercerind/media_kit/tree/main/media_kit). We don't need to make another platform channel abstraction using AVFoundation etc. etc.

See existing GNU/Linux or Windows implementations, only `mpv_handle*` is transferred through platform channels for creating texture etc. while whole player event handling & command issuing is done within Dart using FFI.

Audio only support should be very easy to do, you only need to add macOS support here:

https://github.com/alexmercerind/media_kit/blob/4b02f9caba41df042d59f44b2f65ce8fde2cf1c9/media_kit/lib/src/libmpv/core/native_library.dart#L10-L33

By keeping to use libmpv, we can guarantee that: Firstly, we can do performant hardware accelerated rendering. This might require usage of ANGLE (like on Windows) or maybe not (? I have no prior macOS experience, but I could get it working). Secondly, our existing 100% Dart implementation (FFI-based) will be shared across all 3 platforms (& more that we add) & only video embedding is platform specific.

I have described & documented the complete implementation in the README of project along with detailed class diagrams etc.

**Comment by alexmercerind** [comment]
Or maybe you can use AVFoundation (as long as it doesn't use pixel buffers), will definitely require more work.

**Comment by birros** [comment]
For the record, I am not an expert in macOS, Swift, OpenGL or Metal. But since I need a cross-platform video player for my (private for now) application and media_kit is the most promising one, I try to contribute according to my abilities. So please be kind, I will do my best.

At the moment I am using the AppKit OpenGL Api as the IINA application [does](https://github.com/iina/iina/blob/da1e06cf41c32390356e2b69120cc969bcd31612/iina/ViewLayer.swift#L94-L132), but instead of using a CAOpenGLLayer I am using a [NSOpenGLContext](https://developer.apple.com/documentation/appkit/nsopenglcontext) directly, both of which expose a CGLContextObj. The main drawback of this approach is that the AppKit OpenGL Api is deprecated. But I prefer to follow the IINA approach for now, as I am not an expert.

And don't worry, I'll follow your lead, the goal is to be interoperable with other platforms 😉

**Comment by alexmercerind** [comment]
> For the record, I am not an expert in macOS, Swift, OpenGL or Metal. But since I need a cross-platform video player for my (private for now) application and media_kit is the most promising one, I try to contribute according to my abilities. So please be kind, I will do my best.
> 
> At the moment I am using the AppKit OpenGL Api as the IINA application [does](https://github.com/iina/iina/blob/da1e06cf41c32390356e2b69120cc969bcd31612/iina/ViewLayer.swift#L94-L132), but instead of using a CAOpenGLLayer I am using a [NSOpenGLContext](https://developer.apple.com/documentation/appkit/nsopenglcontext) directly, both of which expose a CGLContextObj. The main drawback of this approach is that the AppKit OpenGL Api is deprecated. But I prefer to follow the IINA approach for now, as I am not an expert.
> 
> And don't worry, I'll follow your lead, the goal is to be interoperable with other platforms 😉

Awesome! Please feel free to reach me out on <saini123hitesh@gmail.com>, if you feel I can provide some information (though I don't claim to be an expert in macOS, Swift, METAL etc.). 

From your comment, I'm really assured that this is going on the right path. IINA is indeed a good example with OpenGL based rendering, shame that I forgot to mention it. There are few other examples here: [`mpv/mpv-examples`](https://github.com/mpv-player/mpv-examples/tree/master/libmpv).

We indeed, yeah need to use OpenGL (not pixel-buffers) for video rendering, like libmpv API allows.
I just wasn't much sure about [situation of OpenGL on macOS](https://news.ycombinator.com/item?id=17231442) [similar to Windows, where Direct3D has always been more performant & stable]. Anyways. We can always switch to ANGLE [approximately zero cost METAL <-> OpenGL translation layer] backend if Apple ever actually removes OpenGL support from their OS (possibly never I believe in reality).

**Comment by Quackdoc** [comment]
feel free to tag me in the PR, I won't be able to look at the code due to time, but I do have a brother with a mac machine and a couple programs I can test at the very least

**Comment by ProgramerMartin** [comment]
I used it on macos #44 
It feels great at first

**Comment by lycstar** [comment]
Is it possible to support iOS with your code @birros

**Comment by birros** [comment]
@lycstar It's planned! I'll finish the pull request #44 first, then I'll try to implement iOS support.

**Comment by lycstar** [comment]
> @lycstar It's planned! I'll finish the pull request #44 first, then I'll try to implement iOS support.

wait your good work
