### ISSUE TITLE
[Enhancement] Provide a track list and track selection methods

### ISSUE THREAD

**Issue by sbenmeddour** [alexmercerind/media_kit#54]
Greetings

Adding the possibility of observing and choosing the tracks would be a great added value for the lib (audio, video and text)

Great work btw, i love your work

**Comment by sbenmeddour** [comment]
Just saw #55
Good timing

**Comment by alexmercerind** [comment]
I'm travelling today, will review or continue myself in that branch tomorrow.

There are a few API changes I'd like to see.

Currently package:media_kit has enough features to target most applications. My current focus is performance (most important for anything serious) & adding support for more platforms.
I'll have to see which features can be part of the "common" `Player` API & which are going to be specialized per backend e.g. libmpv on Windows, GNU/Linux or macOS.
And... If I'm successful in using libmpv on all platforms, all well & good. Still dealing with libmpv bundle size, especially on mobile platforms is going to be a challenge (everything has it's own trade-offs). So, current project architecture is good enough to support any other backend e.g. ExoPlayer or AVFoundation etc. per platform.

**Comment by sbenmeddour** [comment]
#83 implements the request
