### ISSUE TITLE
[Enhancement] media_kit pub.dev page says 'unverified uploader'

### ISSUE THREAD

**Issue by srix55** [alexmercerind/media_kit#56]
![image](https://user-images.githubusercontent.com/6329365/223039525-3b0c454c-56aa-4c0d-86b5-5df69d81dcc0.png)

**Comment by alexmercerind** [comment]
It only becomes "verified" when a domain is registered.

**Comment by srix55** [comment]
Oh ok. I thought it would be as simple as putting in a name & other details...
