### ISSUE TITLE
Setting HTTP headers for a URL source

### ISSUE THREAD

**Issue by postacik** [alexmercerind/media_kit#59]
With better_player package I can set HTTP headers for a URL source as following:

```dart
      var newSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        url,
        drmConfiguration: null,
        headers: {"Cookie": cookie},
      );

```
I tried the same with the extras parameter but could not play the same URL source successfully:

```dart
                      player.open(
                        Playlist(
                          [
                            Media(_video.text, extras: {
                              "Cookie": cookie
                            }),
                          ],
                        ),
                      );

```
Is there a way to set HTTP headers for a URL source?

**Comment by Quackdoc** [comment]
it's not exposed but you can use this 

https://github.com/alexmercerind/media_kit/blob/1074b66694f6c6c858153ec7b779c40cdadcf1f6/media_kit_test/lib/main.dart#L403

with setting this
https://mpv.io/manual/master/#network

**Comment by postacik** [comment]
@Quackdoc Thank you very much. It worked!

```dart
                      if (player.platform is libmpvPlayer) {
                        (player.platform as libmpvPlayer)
                            .setProperty("audio-files", _audio.text);
                        (player.platform as libmpvPlayer).setProperty(
                            "http-header-fields", "Cookie: $cookie");
                      }
                      player.open(
                        Playlist(
                          [
                            Media(_video.text),
                          ],
                        ),
                      );

```

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/3977227/224163725-1b87a1a3-8883-4900-8d2c-1300611ea437.png">

**Comment by Quackdoc** [comment]
closing this for now, but im starting to wonder if there should be a more elegant way to expose these properties. possibly on a per source basis instead of the whole playlist

**Comment by alexmercerind** [comment]
FYI: work in the macOS pull-request [WIP], is not ready for commercial usage.
I assume default INNA libmpv shared libraries include GPL code.

**Comment by postacik** [comment]
@alexmercerind Thanks for the reminder. Just experimenting for my personal use.
