### ISSUE TITLE
[Bug Report][GNU/Linux] Rendering broken on Flutter 3.9.x & Snapshot widget freezes UI on Flutter 3.7.x

### ISSUE THREAD

**Issue by solsticedhiver** [alexmercerind/media_kit#64]
**Edit by @alexmercerind:**

This is a regression in Flutter. I have filed an issue at:
https://github.com/flutter/flutter/issues/124009

Please drop a +1 to that issue for expecting quick fixes.

Thanks!

**Original comment:**

I was testing the plugin player, and couldn't get back in navigator history.

It finally worked, when carefully copying that missing snippet about the `pageTransitionsTheme` of `MaterialApp` theme, that I saw in the media_kit_test example app. Then, it finally worked. But when I tried to use `ZoomPageTransitionBuilder` instead, it didn't work again; meaning I can't go back to my previous route, and the player freeze and the app is stuck/frozen.

This is easily reproduced by modifying the `pageTransitionsTheme` of main.dart (line 25-29) of `media_kit_test`.

**Comment by alexmercerind** [comment]
Bug in Flutter. `Snapshot` widget is buggy in Flutter. Report it to them.

**Comment by alexmercerind** [comment]
Linux specific.

**Comment by solsticedhiver** [comment]
I leave it to you to report that upstream, if need be. Because I wouldn't even know how to describe the bug.

May you could add a hint, in your doc or the example code, about that issue?

**Comment by alexmercerind** [comment]
This is still an issue.

<hr>

Sorry, I don't have time to explain in detail, my schedule is very busy these days. I will be available by the end of this month.

For now, you can read this to get further details: https://github.com/flutter/flutter/issues/117917.

Snapshotting is broken on Flutter GNU/Linux AFAIK. It does not include images either, breaks `Texture` widget etc. etc.

**Comment by solsticedhiver** [comment]
I got this answer in #hackers-new on 
 discord:https://discord.com/channels/608014603317936148/608021635370582020/1087162800209678388

refering to https://github.com/flutter/engine/pull/40208 as a poosible fix of the issue

So I tried flutter's  main and master channel and indeed the transition is working with Zoom but media_kit output video stays black.

I can't say again why if it is flutter's fault or not.

media_kit might be broken in upcoming flutter release

**Comment by alexmercerind** [comment]
I can actually reproduce consistent black screen on `master` channel.
This seems like a regression to me within Flutter itself. What can I do in such situation. Let's see.

**Comment by alexmercerind** [comment]
Hey! I have filed an issue at:

https://github.com/flutter/flutter/issues/124009

Please give that a +1 as can break a large number of Flutter applications that run on GNU/Linux.

**Comment by alexmercerind** [comment]
Congratulations, we prevented the future that never was & thanks to the Flutter team for very quick fix!
Apparently there is a new method for obtaining texture ID, I will update it (would remove support for older Flutter versions).
