### ISSUE TITLE
subtitles are not working

### ISSUE THREAD

**Issue by TSCSOftware** [alexmercerind/media_kit#66]
```
var pp = windowsvidplayer.platform as libmpvPlayer;
      await pp.setProperty("sub-file", "E:\\sub.srt");
      await pp.setProperty("subs-with-matching-audio", "no");
      await pp.setProperty("sub-forced-only", "yes");
      await pp.setProperty("blend-subtitles", "video");
      controller = await VideoController.create(windowsvidplayer.handle);

      setState(() {});

      windowsvidplayer.open(Playlist([dta]));
```

experted
mpv  " https://my-video-path" --sub-file=E:\\sub.srt --subs-with-matching-audio=no --sub-forced-only=yes --blend-subtitles=video

using mpv exe an arggument is working fine;
but setProperty is not working in flutter applixcation

**Comment by alexmercerind** [comment]
See mpv logs etc. You seem familiar with mpv. I'm unsure how is this an issue?
You are using direct mpv APIs which are not exposed by package:media_kit.
