### ISSUE TITLE
[QUESTION] Duration without playing video

### ISSUE THREAD

**Issue by mode234** [alexmercerind/media_kit#67]
Hello Everyone!

As the title says, I'd like to know **is it possible to get duration of the video without playing it**?

Thanks in advance!

**Comment by alexmercerind** [comment]
Not possible.

**Comment by alexmercerind** [comment]
You can certainly read tags, metadata, cover etc. of a media source using this project like [Harmonoid](https://github.com/harmonoid/harmonoid) does.
Certainly out of scope.
