### ISSUE TITLE
rtsp live stream  low delay

### ISSUE THREAD

**Issue by jiangchunyu** [alexmercerind/media_kit#75]
I want to play an rtsp live stream. If I want to set a very low delay, how should I set it? I followed the setup method provided by MPV without success
![image](https://user-images.githubusercontent.com/9071195/227099767-c7041c8e-efd4-48bf-ac49-9e962c8c695a.png)

'''
if (player.platform is libmpvPlayer) {  
 (player.platform as libmpvPlayer)   
   .setProperty("opengl-glfinish", "yes");
 (player.platform as libmpvPlayer)  .setProperty("untimed", "")
....

'''

**Comment by alexmercerind** [comment]
I don't know, the list of options is available to you. Don't ask us for consultancy.
