### ISSUE TITLE
Federated plugin

### ISSUE THREAD

**Issue by hillelcoren** [alexmercerind/media_kit#79]
Hi,

Are there plans to support offering this plugin as a federated plugin of video_player? The API's are different, being able to use this plugin as a federated plugin of video_player would make transitioning between the packages much easier. 

Thanks!

**Comment by alexmercerind** [comment]
No plans [at least in the short term].

package:video_player is very limited, inefficient, nearly un-maintained & missing support for desktop platforms. This repository contains my implementation of an ideal media library that would meet everyone's requirements e.g. RTSP/RTMP, hardware-acceleration (GPU), Windows, Linux, macOS & etc. etc.
Secondly, I have [no interest in helping who don't want to get helped (they just closed it)](https://github.com/flutter/plugins/pull/3712). So, it wouldn't matter anyway.

I started this project for audio playback requirement in [Harmonoid](http://harmonoid.com/). Video embedding is something I implemented once I received some funding from community. To meet requirements of all kinds (audio or video), the project is modularly split into number of packages to efficiently select & bundle the libraries. Refer to class diagrams in the README for more architecture related details.

As stated in the ["Goals" section of README](https://github.com/alexmercerind/media_kit/tree/main#goals):

> The primary goal of [package:media_kit](https://github.com/alexmercerind/media_kit) is to become a **strong, stable, feature-proof & modular** media playback library for Flutter. The idea is to support both **audio & video playback**.
>
> [package:media_kit](https://github.com/alexmercerind/media_kit) makes rendering [**hardware accelerated video playback**](https://github.com/alexmercerind/dart_vlc/issues/345) possible in Flutter.
>
> Since, targetting multiple features at once & bundling redundant native libraries can result in increased bundle size of the application, you can manually select the native libraries you want to bundle, depending upon your use-case. The code is architectured to support multiple platforms & features. Support for more platforms will be added in future.

There are few other notable differences:
- package:media_kit's most code is in Dart i.e. event handling, all methods & API etc. (using FFI).
- package:media_kit's video embedding (only) is platform specific (C/C++/Swift/Obj-C/Java/Kotlin).
- package:media_kit supports both audio & video playback.
- package:media_kit allows to modularly select platform dependencies based on use case.
- package:media_kit is far more powerful & provides stronger API.

All the work that I'm doing here is public & free for usage. I have no interest in answering questions or providing clarifications at the moment. Even though current implementation is really-really performant, there are still many problems. I rather work on the important & difficult challenges here. 

If you want package:media_kit to offer a bridge to package:video_player, feel free to raise a pull request.

<hr>

package:media_kit is already "Federated" into a number of packages to focus on modularity.

**Comment by hillelcoren** [comment]
Ok, understood. Thanks for your response.
