### ISSUE TITLE
Great works! Other platform?

### ISSUE THREAD

**Issue by mount33** [alexmercerind/media_kit#8]
Do you have any plans on mobile (iOS && Android) and MacOS support?

**Comment by alexmercerind** [comment]
Thanks for showing your excitement.

The README has a [Progress](https://github.com/alexmercerind/media_kit#platforms) section which indicates the progress. Currently, only Windows has been implemented, try it out by cloning the repository & running it locally. the video playback should be very good & performant.

The complete idea is to have three modular packages, `package:media_kit`, `package:media_kit_core_audio` & `package:media_kit_core_video` for now. It will reduce the bundle size. More things may come in future. You can see the class diagram, code architecture, documentation in the README.

For now, I do have plans to add support for Linux in upcoming week, and macOS sometime in future depending on my motivation level. Rest, I don't have any self-interest or requirement of video playback in any of my projects, all work here is entirely funding based.
