### ISSUE TITLE
[Enhancement] Possibility to resize the rect of `VideoController`

### ISSUE THREAD

**Issue by bdlukaa** [alexmercerind/media_kit#84]
From the documentation:

```dart
/// 1. You can limit size of the video output by specifying `width` & `height`.
///    By default, both `height` & `width` are `null` i.e. output is based on video's resolution.
```

Currently, I initialize the video with `640x360`, but I find the need to use a smaller resolution when the video is resized (192x144). Would it be possible to change the height and width of the `VideoController`?

I tried to create different video controllers with different resolutions, but it seems that the second controller isn't created if one controller is already initialized. It also crashes when the second controller is initialized. Is that by design?

**Comment by alexmercerind** [comment]
This is going to be fairly large time investment with no real benefits to our most customers. I'll re-evaluate in future.

Implementation, logic changes & most importantly ensuring stability etc. can be challenging.
Most users aren't passing any `width` or `height` anyway.

**Comment by birros** [comment]
I agree with implementing it, I need it for my application too.
Reducing the size of textures reduces CPU and GPU consumption (it makes sense), which I need to play 4K videos on my old MacBook without the fans burning out ^^

> This is going to be fairly large time investment with no real benefits to our most customers.

In fact, I think it can be done relatively quickly, by adding a setter that overrides the `width` and `height` values passed as optional parameters when creating `VideoOutput`.
When these values are non-null, the render size is then "fixed":

https://github.com/alexmercerind/media_kit/blob/03d8a702d5c0600e94548fd68a6b71c1485a0e49/media_kit_video/common/darwin/Classes/VideoOutput.swift#L131-L141

If, when rendering, a different size is found, the texture is resized:

https://github.com/alexmercerind/media_kit/blob/03d8a702d5c0600e94548fd68a6b71c1485a0e49/media_kit_video/common/darwin/Classes/VideoOutput.swift#L111-L117

@alexmercerind  I copied the logic of what you did for Linux and Windows.
(I forgot to rename the `width` and `height` variables to `requiredWidth` and `requiredHeight` like for Linux and Windows).

I will create a pull request to experiment with this for macOS and iOS.

**Comment by alexmercerind** [comment]
I will still stand by my point that this is an overkill. Sure, I will do it for Windows & Linux (now that PR is here).

Being able to pass an initial texture size was already a good feature which no other existing packages offer. We are very good from feature & performance standpoint. My biggest concern is stability, I aim to not touch video embedding code too much in future. Every slight change can result in major issues e.g. threading, rendering, syncing, invalid memory access etc.

A good amount of time needs to be given to the testing afterwards. I aim for those in future (if possible). Let's land this pull request after next release. I want to release API refactor, track selection & macOS/iOS support in this version.

**Comment by alexmercerind** [comment]
> I copied the logic of what you did for Linux and Windows.

It's good to have same degree of similarity. Thanks!
