### ISSUE TITLE
web support

### ISSUE THREAD

**Issue by zezo357** [alexmercerind/media_kit#87]
I saw that the platforms table, doesnt include web

does that mean its not planned? and we need to create a work around to use media_kit with video_player to work across all platforms?

thank you for the package

**Comment by alexmercerind** [comment]
IO platforms are first priority. Web support is definitely coming after Android. 

Please use our Discord for conversations & do not start a questionnaire or discussion here.
I'll gladly answer questions or share plans there.

**Comment by zezo357** [comment]
> IO platforms are first priority. Web support is definitely coming after Android.
> 
> Please use our Discord for conversations & do not start a questionnaire or discussion here. I'll gladly answer questions or share plans there.

ok i will do so, sorry for any inconvenience

**Comment by HankG** [comment]
> Please use our Discord for conversations

I just found this library this weekend when looking for Desktop video players and very impressed with initial dabbling with it. I am looking for the link for the Discord server mentioned here but can't find it in the README. Is that a private discord or is the link missing from the documentation?

**Comment by alexmercerind** [comment]
https://discord.gg/h7qf2R9n57

You may find it at the top of README.
