### ISSUE TITLE
Latest Version Crashes Test App in iOS Simulator on Apple Silicon

### ISSUE THREAD

**Issue by HankG** [alexmercerind/media_kit#98]
Running the latest branch (#97) allows the test app to run in the simulator with a simple `flutter run` out of the box but once one tries to click on a video to run it the app crashes with the below crash dump:
[CrashStackTrace.txt](https://github.com/alexmercerind/media_kit/files/11132417/CrashStackTrace.txt)

**Comment by birros** [comment]
Same crash with the x86_64 simulator, I will be able to debug.
Good news, the use of an xcframework thanks to the pull request #97 allows xcode to select the right platform during the build.
